- simple-operation-library/src/main/java/gaffer/operation/simple/hdfs/handler/jobfactory/TextJobInitialiser.java
Removed copy paste error in TextJobInitialiser
> #21 - Typo: removing copy paste error in TextJobInitialiser.

- .gitignore
- simple-function-library/src/main/java/gaffer/function/simple/filter/MultiRegex.java
- simple-function-library/src/main/java/gaffer/function/simple/filter/Regex.java
- simple-function-library/src/test/java/gaffer/function/simple/filter/MultiRegexTest.java
- simple-function-library/src/test/java/gaffer/function/simple/filter/RegexTest.java
Adding regex filters to the simple-function-library
> G20 expand simple function library

- accumulo-store/src/main/java/gaffer/accumulostore/key/core/impl/CoreKeyColumnQualifierVisibilityValueAggregatorIterator.java
- accumulo-store/src/main/java/gaffer/accumulostore/key/core/impl/byteEntity/ByteEntityAccumuloElementConverter.java
- accumulo-store/src/main/java/gaffer/accumulostore/key/core/impl/classic/ClassicAccumuloElementConverter.java
- accumulo-store/src/main/java/gaffer/accumulostore/key/impl/AggregatorIterator.java
- accumulo-store/src/main/java/gaffer/accumulostore/key/impl/ElementFilter.java
- accumulo-store/src/main/java/gaffer/accumulostore/operation/handler/GetAdjacentEntitySeedsHandler.java
- accumulo-store/src/main/java/gaffer/accumulostore/operation/hdfs/handler/job/AccumuloAddElementsFromHdfsJobFactory.java
- accumulo-store/src/main/java/gaffer/accumulostore/operation/hdfs/handler/job/AddElementsFromHdfsMapper.java
- accumulo-store/src/main/java/gaffer/accumulostore/operation/hdfs/handler/job/AddElementsFromHdfsReducer.java
- accumulo-store/src/main/java/gaffer/accumulostore/utils/Constants.java
- accumulo-store/src/main/java/gaffer/accumulostore/utils/IteratorSettingBuilder.java
- accumulo-store/src/test/java/gaffer/accumulostore/key/core/impl/AbstractAccumuloElementConverterTest.java
- accumulo-store/src/test/java/gaffer/accumulostore/operation/handler/GetAdjacentEntitySeedsHandlerTest.java
- gaffer-core/operation/src/main/java/gaffer/operation/AbstractOperation.java
- gaffer-core/operation/src/main/java/gaffer/operation/Operation.java
- simple-operation-library/src/main/java/gaffer/operation/simple/hdfs/AddElementsFromHdfs.java
- simple-operation-library/src/main/java/gaffer/operation/simple/hdfs/handler/AbstractAddElementsFromHdfsJobFactory.java
As issue G29, also added ability to set the number of mappers for the addFromHdfs task.
> G29 refactor accumulo add elements from hdfs handler

- accumulo-store/pom.xml
- accumulo-store/src/main/java/gaffer/accumulostore/utils/AddUpdateTableIterator.java
- gaffer-core/graph/src/main/java/gaffer/graph/Graph.java
- gaffer-core/store/src/main/java/gaffer/store/StoreProperties.java
> Adding a maintenence jar to be built with the accumulo store, this jar

- .travis.yml
- pom.xml
Another attempt to fix travis. I have set the fork count to 0 and disabled findbugs to reduce memory consumption. This currently seems to work.
> G58 fix travis 2

- accumulo-store/src/main/java/gaffer/accumulostore/operation/AbstractAccumuloTwoSetSeededOperation.java
- accumulo-store/src/main/java/gaffer/accumulostore/operation/impl/GetEdgesBetweenSets.java
- accumulo-store/src/main/java/gaffer/accumulostore/operation/impl/GetEdgesInRanges.java
- accumulo-store/src/main/java/gaffer/accumulostore/operation/impl/GetEdgesWithinSet.java
- accumulo-store/src/main/java/gaffer/accumulostore/operation/impl/GetElementsBetweenSets.java
- accumulo-store/src/main/java/gaffer/accumulostore/operation/impl/GetElementsInRanges.java
- accumulo-store/src/main/java/gaffer/accumulostore/operation/impl/GetElementsWithinSet.java
- accumulo-store/src/main/java/gaffer/accumulostore/operation/impl/GetEntitiesInRanges.java
- gaffer-core/operation/src/main/java/gaffer/operation/AbstractGetOperation.java
- gaffer-core/operation/src/main/java/gaffer/operation/impl/get/GetAdjacentEntitySeeds.java
- gaffer-core/operation/src/main/java/gaffer/operation/impl/get/GetEdgesBySeed.java
- gaffer-core/operation/src/main/java/gaffer/operation/impl/get/GetElementsSeed.java
- gaffer-core/operation/src/main/java/gaffer/operation/impl/get/GetRelatedEdges.java
- gaffer-core/operation/src/main/java/gaffer/operation/impl/get/GetRelatedElements.java
- gaffer-integration-tests/src/test/java/gaffer/integration/impl/GetAdjacentEntitySeedsIT.java
Also updated accumulo builders
> gh-130 - Added in out type method to builders

- accumulo-store/src/main/java/gaffer/accumulostore/AccumuloStore.java
- accumulo-store/src/test/java/gaffer/accumulostore/AccumuloStoreTest.java
- array-list-store/src/main/java/gaffer/arrayliststore/ArrayListStore.java
- gaffer-core/graph/src/main/java/gaffer/graph/Graph.java
- gaffer-core/graph/src/test/java/gaffer/graph/GraphTest.java
- gaffer-core/graph/src/test/java/gaffer/integration/store/TestStore.java
- gaffer-core/store/src/main/java/gaffer/store/Store.java
- gaffer-core/store/src/test/java/gaffer/integration/StoreIT.java
- gaffer-core/store/src/test/java/gaffer/store/StoreTest.java
- rest-api/src/main/java/gaffer/rest/service/IGraphConfigurationService.java
- rest-api/src/main/java/gaffer/rest/service/SimpleGraphConfigurationService.java
- rest-api/src/test/java/gaffer/rest/service/SimpleGraphConfigurationServiceTest.java
Expose the Store Traits that are supported by the Store to the Rest Service and the Graph
> G145 get store traits

- gaffer-core/store/src/test/java/gaffer/store/schema/SchemaTest.java
The functionality was covered in other unit tests
> gh-173 - spaces in directory

- accumulo-store/src/main/java/gaffer/accumulostore/operation/hdfs/handler/job/SampleDataForSplitPointsJobFactory.java
- accumulo-store/src/main/java/gaffer/accumulostore/operation/hdfs/handler/job/SampleDataForSplitPointsMapper.java
Changed SampleDataForSplitPointsMapper to extend base AbstractAddElementsFromHdfsMapper
> gh-309 Set ACCUMULO_ELEMENT_CONVERTER_CLASS in job factory.

- gaffer-core/serialisation/src/main/java/gaffer/exception/SerialisationException.java
- pom.xml
- simple-function-library/pom.xml
- simple-function-library/src/main/java/gaffer/function/simple/aggregate/FreqMapAggregator.java
- simple-function-library/src/main/java/gaffer/function/simple/filter/FreqMapIsMoreThan.java
- simple-function-library/src/test/java/gaffer/function/simple/aggregate/FreqMapAggregatorTest.java
- simple-function-library/src/test/java/gaffer/function/simple/filter/FreqMapIsMoreThanTest.java
- simple-serialisation-library/pom.xml
- simple-serialisation-library/src/main/java/gaffer/serialisation/simple/FreqMapSerialiser.java
- simple-serialisation-library/src/test/java/gaffer/serialisation/simple/FreqMapSerialiserTest.java
- simple-serialisation-library/src/test/java/gaffer/serialisation/simple/json/hyperloglogplus/HyperLogLogPlusJsonSerialisationTest.java
- simple-types-library/pom.xml
- simple-types-library/src/main/java/gaffer/types/simple/FreqMap.java
Moved The Frequency Map object into the simple-types-library so it could be shared between the simple serialisation and simple functions project
> gh-313 Added Frequency map serialiser

- accumulo-store/src/test/java/gaffer/accumulostore/integration/performance/BloomFilterIT.java
- pom.xml
Updated Test to remove transient dependency
> gh-324 Updated master Pom to use Accumulo 1.7.2 and Hadoop 2.6.3

- NOTICES
- example/pom.xml
- gaffer-integration-tests/pom.xml
- pom.xml
- rest-api/pom.xml
Also changed poms to use version properties
> gh-351 - updated dependency versions in NOTICES file.

- rest-api/pom.xml
- ui/src/main/webapp/app/controller.js
- ui/src/main/webapp/app/raw/raw.js
Also fixed jar warnings when REST API is started and a minor bug with the loading spinner
> gh-451 - added groupBy field to operations created in the UI

- .travis.yml
Updated .travis.yml to pull in the most recent available version of the JDK from the APT repository.
> Gh 480 update travis

- docs/checkstyle.xml
Enforcing use of final keyword for:
- method parameters
- constructor parameters
- enhanced for loops
> gh-220 - Updated checkstyle.xml to enforce project preferences regarding final values

- .travis.yml
- pom.xml
Second attempt to add codecov integration.
> Gh 142 codecov v2 - testing

- core/data/src/main/java/uk/gov/gchq/gaffer/data/elementdefinition/view/ViewElementDefinition.java
- core/data/src/test/java/uk/gov/gchq/gaffer/data/elementdefinition/view/ViewElementDefinitionTest.java
I've chosen the IllegalArgumentException for this issue - let me know if you think something else would be more appropriate.
> gh-513 - Added validation to the ViewElementDefinition builder class.

- core/serialisation/src/main/java/uk/gov/gchq/gaffer/serialisation/AbstractSerialisation.java
- library/sketches-library/src/main/java/uk/gov/gchq/gaffer/sketches/function/filter/HyperLogLogPlusIsLessThan.java
Fix for issues gh-607 and gh-608.
> gh-607-608 - Fix Javadoc issues.

- core/graph/src/main/java/uk/gov/gchq/gaffer/graph/Graph.java
- core/graph/src/test/java/uk/gov/gchq/gaffer/graph/GraphTest.java
- core/store/src/main/java/uk/gov/gchq/gaffer/store/StoreProperties.java
It creates an empty properties object to get/set properties in.
> gh-707 - default constructor for store properties now works

- ui/src/main/webapp/app/controller.js
String seeds are now automatically quoted. To use an integer as a string seed you will need to put the value in quotes.
It is not a particularly nice implementation but it'll do until we get a better/proper UI.
> gh-724 - string seeds are now automatically quoted

- README.md
> Update README.md with link to CLA.

- store-implementation/accumulo-store/src/main/java/uk/gov/gchq/gaffer/accumulostore/retriever/AccumuloItemRetriever.java
- store-implementation/accumulo-store/src/main/java/uk/gov/gchq/gaffer/accumulostore/retriever/impl/AccumuloAllElementsRetriever.java
Modified AccumuloAllElementsRetriever to use the ItemRetriever super class - will now correctly apply transformation functions and the common parent should make the AccumuloAllElementsRetriever more resilient to change.
> gh-828 - AccumuloAllElementsRetriever Should apply post transformation functions

- NOTICES
- core/data/src/test/java/uk/gov/gchq/gaffer/data/element/function/ElementFilterTest.java
- core/store/src/main/java/uk/gov/gchq/gaffer/store/schema/SchemaElementDefinition.java
- core/store/src/test/java/uk/gov/gchq/gaffer/store/schema/SchemaElementDefinitionValidatorTest.java
- core/store/src/test/java/uk/gov/gchq/gaffer/store/schema/ViewValidatorTest.java
- doc/src/main/java/uk/gov/gchq/gaffer/doc/predicate/AndExample.java
- doc/src/main/java/uk/gov/gchq/gaffer/doc/predicate/OrExample.java
- doc/src/main/java/uk/gov/gchq/gaffer/doc/predicate/PredicateExample.java
- library/spark/spark-accumulo-library/src/test/java/uk/gov/gchq/gaffer/sparkaccumulo/operation/handler/dataframe/AccumuloStoreRelationTest.java
- library/spark/spark-library/src/main/java/uk/gov/gchq/gaffer/spark/operation/dataframe/FiltersToOperationConverter.java
- pom.xml
koryphe version 0.1.1 fixes several validation issues with predicates
> gh-877 - updated to use the koryphe version 0.1.1

- core/common-util/src/main/java/uk/gov/gchq/gaffer/commonutil/CloseableUtil.java
- core/common-util/src/test/java/uk/gov/gchq/gaffer/commonutil/CloseableUtilTest.java
- core/graph/src/main/java/uk/gov/gchq/gaffer/graph/hook/OperationChainLimiter.java
- core/operation/src/main/java/uk/gov/gchq/gaffer/operation/impl/ScoreOperationChain.java
- core/operation/src/main/java/uk/gov/gchq/gaffer/operation/serialisation/TypeReferenceImpl.java
- core/store/README.md
- core/store/src/main/java/uk/gov/gchq/gaffer/store/operation/handler/ScoreOperationChainHandler.java
- core/store/src/main/resources/ScoreOperationChainDeclaration.json
- core/store/src/test/java/uk/gov/gchq/gaffer/store/operation/handler/ScoreOperationChainHandlerTest.java
- core/store/src/test/resources/ScoreOperationChainDeclarationNoFileNames.json
- core/store/src/test/resources/TestScoreOperationChainDeclaration.json
- core/store/src/test/resources/authScores.properties
- core/store/src/test/resources/customOpScores.properties
- core/store/src/test/resources/opScores.properties
- rest-api/core-rest/src/main/java/uk/gov/gchq/gaffer/rest/SystemProperty.java
- rest-api/core-rest/src/main/java/uk/gov/gchq/gaffer/rest/factory/DefaultGraphFactory.java
- Created a new operation - ScoreOperationChain
- Moved the score logic from OperationChainLimiter to ScoreOperationChainHandler to avoid duplication.
> gh-991 - added ScoreOperationChain operation

- library/spark/spark-accumulo-library/src/main/java/uk/gov/gchq/gaffer/sparkaccumulo/operation/utils/AccumuloKeyRangePartitioner.java
- store-implementation/accumulo-store/src/main/java/uk/gov/gchq/gaffer/accumulostore/AccumuloStore.java
- store-implementation/accumulo-store/src/main/java/uk/gov/gchq/gaffer/accumulostore/SingleUseAccumuloStore.java
- store-implementation/accumulo-store/src/main/java/uk/gov/gchq/gaffer/accumulostore/SingleUseMockAccumuloStore.java
- store-implementation/accumulo-store/src/main/java/uk/gov/gchq/gaffer/accumulostore/operation/hdfs/handler/AddElementsFromHdfsHandler.java
- store-implementation/accumulo-store/src/main/java/uk/gov/gchq/gaffer/accumulostore/operation/hdfs/handler/SplitStoreHandler.java
- store-implementation/accumulo-store/src/main/java/uk/gov/gchq/gaffer/accumulostore/operation/hdfs/handler/job/factory/AccumuloAddElementsFromHdfsJobFactory.java
- store-implementation/accumulo-store/src/main/java/uk/gov/gchq/gaffer/accumulostore/operation/hdfs/handler/job/tool/ImportElementsToAccumuloTool.java
- store-implementation/accumulo-store/src/main/java/uk/gov/gchq/gaffer/accumulostore/retriever/AccumuloRetriever.java
- store-implementation/accumulo-store/src/main/java/uk/gov/gchq/gaffer/accumulostore/utils/AddUpdateTableIterator.java
- store-implementation/accumulo-store/src/main/java/uk/gov/gchq/gaffer/accumulostore/utils/TableUtils.java
- store-implementation/accumulo-store/src/test/java/uk/gov/gchq/gaffer/accumulostore/AccumuloStoreTest.java
- store-implementation/accumulo-store/src/test/java/uk/gov/gchq/gaffer/accumulostore/integration/AddElementsFromHdfsIT.java
- store-implementation/accumulo-store/src/test/java/uk/gov/gchq/gaffer/accumulostore/integration/CreateSplitPointsIT.java
- store-implementation/accumulo-store/src/test/java/uk/gov/gchq/gaffer/accumulostore/key/core/impl/CoreKeyGroupByAggregatorIteratorTest.java
- store-implementation/accumulo-store/src/test/java/uk/gov/gchq/gaffer/accumulostore/key/impl/RowIdAggregatorTest.java
- store-implementation/hbase-store/src/main/java/uk/gov/gchq/gaffer/hbasestore/HBaseStore.java
- store-implementation/hbase-store/src/main/java/uk/gov/gchq/gaffer/hbasestore/operation/hdfs/handler/AddElementsFromHdfsHandler.java
- store-implementation/hbase-store/src/main/java/uk/gov/gchq/gaffer/hbasestore/operation/hdfs/handler/job/factory/HBaseAddElementsFromHdfsJobFactory.java
- store-implementation/hbase-store/src/main/java/uk/gov/gchq/gaffer/hbasestore/utils/TableUtils.java
- store-implementation/hbase-store/src/test/java/uk/gov/gchq/gaffer/hbasestore/HBasePropertiesTest.java
- store-implementation/hbase-store/src/test/java/uk/gov/gchq/gaffer/hbasestore/HBaseStoreTest.java
- store-implementation/hbase-store/src/test/java/uk/gov/gchq/gaffer/hbasestore/integration/StandaloneHBaseStoreSTs.java
- store-implementation/hbase-store/src/test/java/uk/gov/gchq/gaffer/hbasestore/util/TableUtilsTest.java
Added this for the Accumulo and HBase stores. This is required for issue gh-954. The rest of the changes are coming later
> gh-954 - created getTableName method

- core/store/src/main/java/uk/gov/gchq/gaffer/store/Store.java
- core/store/src/main/java/uk/gov/gchq/gaffer/store/StoreProperties.java
- core/store/src/test/java/uk/gov/gchq/gaffer/store/StorePropertiesTest.java
- pom.xml
- rest-api/accumulo-rest/pom.xml
- rest-api/accumulo-rest/src/main/resources/disableOperations.json
- rest-api/accumulo-rest/src/test/java/uk/gov/gchq/gaffer/rest/factory/AccumuloDisableOperationsTest.java
- rest-api/accumulo-rest/src/test/resources/store.properties
- rest-api/core-rest/src/main/java/uk/gov/gchq/gaffer/rest/factory/DefaultGraphFactory.java
- rest-api/core-rest/src/main/resources/disableOperations.json
- rest-api/core-rest/src/test/java/uk/gov/gchq/gaffer/rest/DisableOperationsTest.java
- rest-api/hbase-rest/pom.xml
- rest-api/hbase-rest/src/main/resources/disableOperations.json
- rest-api/hbase-rest/src/test/java/uk/gov/gchq/gaffer/rest/factory/HBaseDisableOperationsTest.java
- rest-api/hbase-rest/src/test/resources/store.properties
- store-implementation/hbase-store/pom.xml
Replacement for pull request #1022
> gh-113 - disables operations in rest api

- core/operation/README.md
- doc/src/main/java/uk/gov/gchq/gaffer/doc/operation/GetElementsExample.java
- doc/src/main/java/uk/gov/gchq/gaffer/doc/operation/OperationExample.java
- doc/src/main/java/uk/gov/gchq/gaffer/doc/predicate/AgeOffExample.java
- doc/src/main/java/uk/gov/gchq/gaffer/doc/predicate/AndExample.java
- doc/src/main/java/uk/gov/gchq/gaffer/doc/predicate/AreEqualExample.java
- doc/src/main/java/uk/gov/gchq/gaffer/doc/predicate/AreInExample.java
- doc/src/main/java/uk/gov/gchq/gaffer/doc/predicate/CollectionContainsExample.java
- doc/src/main/java/uk/gov/gchq/gaffer/doc/predicate/ExistsExample.java
- doc/src/main/java/uk/gov/gchq/gaffer/doc/predicate/HyperLogLogPlusIsLessThanExample.java
- doc/src/main/java/uk/gov/gchq/gaffer/doc/predicate/IsAExample.java
- doc/src/main/java/uk/gov/gchq/gaffer/doc/predicate/IsEqualExample.java
- doc/src/main/java/uk/gov/gchq/gaffer/doc/predicate/IsFalseExample.java
- doc/src/main/java/uk/gov/gchq/gaffer/doc/predicate/IsInExample.java
- doc/src/main/java/uk/gov/gchq/gaffer/doc/predicate/IsLessThanExample.java
- doc/src/main/java/uk/gov/gchq/gaffer/doc/predicate/IsMoreThanExample.java
- doc/src/main/java/uk/gov/gchq/gaffer/doc/predicate/IsShorterThanExample.java
- doc/src/main/java/uk/gov/gchq/gaffer/doc/predicate/IsTrueExample.java
- doc/src/main/java/uk/gov/gchq/gaffer/doc/predicate/IsXLessThanYExample.java
- doc/src/main/java/uk/gov/gchq/gaffer/doc/predicate/IsXMoreThanYExample.java
- doc/src/main/java/uk/gov/gchq/gaffer/doc/predicate/MapContainsExample.java
- doc/src/main/java/uk/gov/gchq/gaffer/doc/predicate/MapFilterExample.java
- doc/src/main/java/uk/gov/gchq/gaffer/doc/predicate/MultiRegexExample.java
- doc/src/main/java/uk/gov/gchq/gaffer/doc/predicate/NotExample.java
- doc/src/main/java/uk/gov/gchq/gaffer/doc/predicate/OrExample.java
- doc/src/main/java/uk/gov/gchq/gaffer/doc/predicate/PredicateExample.java
- doc/src/main/java/uk/gov/gchq/gaffer/doc/predicate/RegexExample.java
Update the OrExample and added an Or example to the GetElementsExample to explain how to use an Or predicate
> gh-838 - added faq to operations readme

- core/type/src/main/java/uk/gov/gchq/gaffer/types/TypeSubTypeValue.java
- core/type/src/main/java/uk/gov/gchq/gaffer/types/TypeValue.java
- core/type/src/test/java/uk/gov/gchq/gaffer/types/TypeSubTypeValueTest.java
- core/type/src/test/java/uk/gov/gchq/gaffer/types/TypeValueTest.java
Adding compareTo methods on TypeSubTypeValue and TypeValue additionally added a toString method on TypeSubTypeValue
> gh-1076 Adding compareTo methods on TypeSubTypeValue and TypeValue 

- core/graph/src/test/java/uk/gov/gchq/gaffer/operation/export/graph/ExportToOtherAuthorisedGraphTest.java
- core/graph/src/test/java/uk/gov/gchq/gaffer/operation/export/graph/ExportToOtherGraphTest.java
- core/operation/src/test/java/uk/gov/gchq/gaffer/operation/OperationTest.java
- core/operation/src/test/java/uk/gov/gchq/gaffer/operation/impl/add/AddElementsFromFileTest.java
- core/operation/src/test/java/uk/gov/gchq/gaffer/operation/impl/add/AddElementsFromKafkaTest.java
- core/operation/src/test/java/uk/gov/gchq/gaffer/operation/impl/add/AddElementsFromSocketTest.java
Field in OperationTest removed, imports in subclasses added to use field from JsonSerialisationTest interface.
> gh-1184 - Removed duplicated field, resolved imports

- rest-api/core-rest/src/main/java/uk/gov/gchq/gaffer/rest/service/v2/example/DefaultExamplesFactory.java
- rest-api/core-rest/src/main/webapp/css/gaffer.css
- rest-api/core-rest/src/main/webapp/index.html
- rest-api/core-rest/src/main/webapp/lib/gaffer.js
To test this:
- start the example rest api
- go to operations/execute
- in the dropdown select an operation
- click add example
- select another operation
- click add example again
This will add 2 examples in an operation chain.
> gh-1267 - updated example button in swagger

- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreTest.java
Added tests for the Get Graphs by a CSV string method in the Federated Store.
> gh-1257 - Added test for getGraphs by CSV string

- example/road-traffic/road-traffic-generators/src/main/java/uk/gov/gchq/gaffer/traffic/generator/RoadTrafficElementGenerator.java
- example/road-traffic/road-traffic-rest/src/test/java/uk.gov.gchq.gaffer.traffic/RoadTrafficRestApiITs.java
- example/road-traffic/road-traffic-rest/src/test/java/uk.gov.gchq.gaffer.traffic/RoadTrafficRestApiSTs.java
- example/road-traffic/road-traffic-rest/src/test/java/uk.gov.gchq.gaffer.traffic/RoadTrafficTestQueries.java
A lot of the changes is just changing tabs to spaces.
> gh-1372 - set the generator to use UTC

- core/common-util/src/main/java/uk/gov/gchq/gaffer/commonutil/GroupUtil.java
- core/common-util/src/main/java/uk/gov/gchq/gaffer/commonutil/PropertiesUtil.java
- core/common-util/src/test/java/uk/gov/gchq/gaffer/commonutil/GroupUtilTest.java
- core/common-util/src/test/java/uk/gov/gchq/gaffer/commonutil/PropertiesUtilTest.java
Regex updated to allow the use of hyphens
Updated unit tests to include hyphens
> gh-1433 - Updated regex and unit tests

- rest-api/core-rest/src/main/java/uk/gov/gchq/gaffer/rest/ServiceConstants.java
- rest-api/core-rest/src/main/java/uk/gov/gchq/gaffer/rest/service/v1/SwaggerDefinitionConfig.java
- rest-api/core-rest/src/main/java/uk/gov/gchq/gaffer/rest/service/v2/SwaggerDefinitionConfigV2.java
Wiki link updated
Checked working in REST API
> gh-1418 - Updated wiki link

- rest-api/core-rest/src/main/java/uk/gov/gchq/gaffer/rest/service/v2/example/DefaultExamplesFactory.java
- rest-api/core-rest/src/main/java/uk/gov/gchq/gaffer/rest/service/v2/example/ExamplesFactory.java
> sort example

- core/graph/src/main/java/uk/gov/gchq/gaffer/graph/Graph.java
- core/graph/src/main/java/uk/gov/gchq/gaffer/graph/hook/AddOperationsToChain.java
- core/graph/src/main/java/uk/gov/gchq/gaffer/graph/hook/OperationAuthoriser.java
- core/graph/src/test/java/uk/gov/gchq/gaffer/graph/hook/AddOperationsToChainTest.java
- core/graph/src/test/java/uk/gov/gchq/gaffer/graph/hook/OperationAuthoriserTest.java
- core/graph/src/test/java/uk/gov/gchq/gaffer/operation/TestOperationsImpl.java
- core/operation/src/main/java/uk/gov/gchq/gaffer/operation/OperationChain.java
- core/operation/src/main/java/uk/gov/gchq/gaffer/operation/Operations.java
- core/operation/src/test/java/uk/gov/gchq/gaffer/operation/OperationChainTest.java
- core/operation/src/test/java/uk/gov/gchq/gaffer/operation/OperationsTest.java
- core/store/src/main/java/uk/gov/gchq/gaffer/store/operation/handler/ScoreOperationChainHandler.java
- core/store/src/test/java/uk/gov/gchq/gaffer/store/operation/handler/ScoreOperationChainHandlerTest.java
- rest-api/core-rest/src/main/java/uk/gov/gchq/gaffer/rest/service/v2/JobServiceV2.java
- rest-api/core-rest/src/main/java/uk/gov/gchq/gaffer/rest/service/v2/OperationServiceV2.java
New interface "Operations" for dealing with classes that contain a Collection of Operations, such as OperationChain, and the upcoming Path operation.
Refactored to deal with recursive handling of nested operations, using the new interface.
> Gh-1443 Operations Interface

- rest-api/README.md
- rest-api/core-rest/src/main/webapp/css/custom.css
- rest-api/core-rest/src/main/webapp/index.html
Added documentation on how to modify the rest api for your project
> gh-1423 - updated rest api readme

- core/data/src/main/java/uk/gov/gchq/gaffer/data/generator/CsvGenerator.java
- core/store/src/test/java/uk/gov/gchq/gaffer/store/operation/handler/output/ToCsvHandlerTest.java
> gh-1595 - commas are now escaped

- rest-api/core-rest/src/main/java/uk/gov/gchq/gaffer/rest/application/ApplicationConfig.java
- rest-api/core-rest/src/main/java/uk/gov/gchq/gaffer/rest/application/ApplicationConfigV1.java
- rest-api/core-rest/src/main/java/uk/gov/gchq/gaffer/rest/application/ApplicationConfigV2.java
- rest-api/core-rest/src/main/java/uk/gov/gchq/gaffer/rest/factory/UserFactory.java
- rest-api/core-rest/src/main/java/uk/gov/gchq/gaffer/rest/service/v2/IGraphConfigurationServiceV2.java
- rest-api/core-rest/src/main/java/uk/gov/gchq/gaffer/rest/service/v2/IJobServiceV2.java
- rest-api/core-rest/src/main/java/uk/gov/gchq/gaffer/rest/service/v2/IOperationServiceV2.java
- rest-api/core-rest/src/main/java/uk/gov/gchq/gaffer/rest/service/v2/IPropertiesServiceV2.java
- rest-api/core-rest/src/main/java/uk/gov/gchq/gaffer/rest/service/v2/IStatusServiceV2.java
- rest-api/core-rest/src/main/java/uk/gov/gchq/gaffer/rest/service/v2/SwaggerDefinitionConfigV2.java
- rest-api/core-rest/src/main/java/uk/gov/gchq/gaffer/rest/service/v2/example/ExamplesFactory.java
Improved verbosity of many annotations for Swagger.
Cleanup/improvement of some Javadoc.
Added notes (where necessary) to most endpoints, providing a terse description of the functionality and usage of a given endpoint.
> Gh-1570 Swagger Doc Improvements

- core/graph/src/main/java/uk/gov/gchq/gaffer/graph/Graph.java
- core/graph/src/test/java/uk/gov/gchq/gaffer/graph/GraphTest.java
- core/store/src/main/java/uk/gov/gchq/gaffer/store/Context.java
- core/store/src/test/java/uk/gov/gchq/gaffer/store/ContextTest.java
- core/store/src/test/java/uk/gov/gchq/gaffer/store/operation/handler/job/GetJobDetailsHandlerTest.java
- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedGraphStorageTest.java
- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/operation/handler/FederatedOperationHandlerTest.java
When operations are executed on a graph a new context object will be created, containing a new jobId
> gh-1662 - forces the context to be updated

- core/graph/src/main/java/uk/gov/gchq/gaffer/graph/Graph.java
- core/graph/src/main/java/uk/gov/gchq/gaffer/operation/export/graph/handler/GraphDelegate.java
- core/graph/src/test/java/uk/gov/gchq/gaffer/graph/GraphTest.java
- core/graph/src/test/java/uk/gov/gchq/gaffer/operation/export/graph/handler/ExportToOtherGraphHandlerTest.java
- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreTest.java
- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/operation/handler/impl/FederatedAddGraphHandlerTest.java
If a schema is null or empty the graph will now fetch it from the store.
> gh-1680 - updated graph builder to get schema from store

- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedStore.java
AddNamedOperation and AddNamedView should now be handled in the normal way
> gh-1682 - updated the logic used to override handlers

- core/store/src/main/java/uk/gov/gchq/gaffer/store/operation/handler/ScoreOperationChainHandler.java
- core/store/src/main/java/uk/gov/gchq/gaffer/store/operation/resolver/DefaultScoreResolver.java
- core/store/src/test/java/uk/gov/gchq/gaffer/store/operation/handler/ScoreOperationChainHandlerTest.java
- core/store/src/test/java/uk/gov/gchq/gaffer/store/operation/resolver/DefaultScoreResolverTest.java
DefaultScoreResolver now resolves the score for nested operations recursively.
Updated tests.
> gh-1690 - refactored DefaultScoreResolver, added tests

- core/graph/src/main/java/uk/gov/gchq/gaffer/graph/Graph.java
- core/graph/src/main/java/uk/gov/gchq/gaffer/graph/GraphConfig.java
- core/graph/src/test/java/uk/gov/gchq/gaffer/graph/hook/AddOperationsToChainTest.java
- core/serialisation/src/main/java/uk/gov/gchq/gaffer/serialisation/util/JsonSerialisationUtil.java
Project now builds under Java 9, specifically:
```java -version```
> java version "9.0.4"
> Java(TM) SE Runtime Environment (build 9.0.4+11)
> Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)
> gh-1722 - Removed usages of sun.* APIs.

- core/data/src/main/java/uk/gov/gchq/gaffer/data/elementdefinition/ElementDefinitions.java
- core/data/src/main/java/uk/gov/gchq/gaffer/data/elementdefinition/view/View.java
- core/data/src/test/java/uk/gov/gchq/gaffer/data/elementdefinition/view/ViewTest.java
- core/graph/src/main/java/uk/gov/gchq/gaffer/graph/hook/UpdateViewHook.java
- core/graph/src/test/java/uk/gov/gchq/gaffer/graph/hook/UpdateViewHookTest.java
Filtering now doesn't override the merged view
> gh-1723 - fixed logic in update view hook

- core/graph/src/main/java/uk/gov/gchq/gaffer/graph/GraphSerialisable.java
- core/graph/src/main/java/uk/gov/gchq/gaffer/operation/export/graph/handler/GraphDelegate.java
- core/store/src/main/java/uk/gov/gchq/gaffer/store/operation/OperationChainValidator.java
- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedGraphStorage.java
- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedStore.java
- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/operation/AddGraphWithHooks.java
- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/operation/FederatedOperationChain.java
- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/operation/handler/FederatedAddGraphHandlerParent.java
- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/operation/handler/impl/FederatedAddGraphHandler.java
- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/operation/handler/impl/FederatedAddGraphWithHooksHandler.java
- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/operation/handler/impl/FederatedOperationChainHandler.java
- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedGraphStorageTest.java
- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreTest.java
- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/PredefinedFederatedStore.java
- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/operation/AddGraphWithHooksTest.java
- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/operation/handler/impl/FederatedAddGraphHandlerTest.java
- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/operation/handler/impl/FederatedAddGraphWithHooksHandlerTest.java
- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/operation/handler/impl/FederatedOperationChainHandlerTest.java
- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/operation/handler/impl/FederatedRemoveGraphHandlerTest.java
Also updated federated op chain so it now implements Input
> gh-1764 - graphs are now validated before being initialised

- core/serialisation/src/main/java/uk/gov/gchq/gaffer/jsonserialisation/JSONSerialiser.java
- rest-api/core-rest/src/main/webapp/lib/gaffer.js
Also fixed an issue with updating the swagger footer
> gh-1796 - disabled strict json by default

- integration-test/src/test/java/uk/gov/gchq/gaffer/integration/impl/StoreValidationIT.java
shouldAgeOfDataBasedOnTimestampAndAgeOfFunctionInSchema -> shouldAgeOffDataBasedOnTimestampAndAgeOffFunctionInSchema
> Correct typo in test method name

- core/store/src/main/java/uk/gov/gchq/gaffer/store/Context.java
- core/store/src/test/java/uk/gov/gchq/gaffer/store/operation/handler/SetVariableHandlerTest.java
> gh-2002 - removed immutable map from Context Variables and test added

- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/operation/FederatedOperationChainValidator.java
- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/operation/FederatedOperationChainValidatorTest.java
- store-implementation/proxy-store/src/main/java/uk/gov/gchq/gaffer/proxystore/operation/handler/OperationChainHandler.java
- store-implementation/proxy-store/src/test/java/uk/gov/gchq/gaffer/proxystore/integration/ProxyStoreBasicIT.java
Switch statement errors when receiving null.
> 1.8.0-RC4-fix

- core/operation/src/main/java/uk/gov/gchq/gaffer/operation/impl/join/Join.java
- core/operation/src/test/java/uk/gov/gchq/gaffer/operation/impl/JoinTest.java
> gh-2119 Add Create Input Array to Join Operation

- core/operation/src/test/java/uk/gov/gchq/gaffer/operation/impl/JoinTest.java
> gh-2142 Removed 3 unused imports

- store-implementation/accumulo-store/README.md
- store-implementation/accumulo-store/src/main/java/uk/gov/gchq/gaffer/accumulostore/AccumuloProperties.java
- store-implementation/accumulo-store/src/main/java/uk/gov/gchq/gaffer/accumulostore/AccumuloStore.java
- store-implementation/accumulo-store/src/main/java/uk/gov/gchq/gaffer/accumulostore/utils/TableUtils.java
- store-implementation/accumulo-store/src/test/java/uk/gov/gchq/gaffer/accumulostore/AccumuloPropertiesTest.java
- store-implementation/accumulo-store/src/test/java/uk/gov/gchq/gaffer/accumulostore/AccumuloStoreTest.java
> gh-2167 allow use of namespace in accumulo store

- cd/deploy.sh
Replace Deprecated Authorisation Method #2271
> Fix for Deprecated Authorisation Method #2271

- .github/workflows/release.yaml
> gh-2378 updated references

- core/operation/src/test/java/uk/gov/gchq/gaffer/operation/OperationTest.java
- core/serialisation/src/test/java/uk/gov/gchq/gaffer/JSONSerialisationTest.java
- library/spark/spark-library/src/main/java/uk/gov/gchq/gaffer/spark/operation/graphframe/GetGraphFrameOfElements.java
> gh-2364 Fixed typos from assumeTrue to assertTrue

- rest-api/core-rest/src/main/java/uk/gov/gchq/gaffer/rest/service/v2/GraphConfigurationServiceV2.java
- rest-api/core-rest/src/main/java/uk/gov/gchq/gaffer/rest/service/v2/IGraphConfigurationServiceV2.java
- rest-api/core-rest/src/test/java/uk/gov/gchq/gaffer/rest/service/v2/GraphConfigurationServiceV2Test.java
> gh-2411 Added swagger endpoint to get graphId

- rest-api/spring-rest/src/main/java/uk/gov/gchq/gaffer/rest/controller/GraphConfigurationController.java
- rest-api/spring-rest/src/main/java/uk/gov/gchq/gaffer/rest/controller/IGraphConfigurationController.java
- rest-api/spring-rest/src/test/java/uk/gov/gchq/gaffer/rest/controller/GraphConfigurationControllerTest.java
- rest-api/spring-rest/src/test/java/uk/gov/gchq/gaffer/rest/integration/controller/GraphConfigurationControllerIT.java
> Added getGraphId endpoint to spring-rest

- integration-test/src/test/java/uk/gov/gchq/gaffer/integration/impl/IfIT.java
- store-implementation/proxy-store/src/main/java/uk/gov/gchq/gaffer/proxystore/response/deserialiser/impl/DefaultResponseDeserialiser.java
- store-implementation/proxy-store/src/test/java/uk/gov/gchq/gaffer/proxystore/response/deserialiser/impl/DefaultResponseDeserialiserTest.java
Added special handling for String values which cannot be parsed using the Jackson deserialiser - only in cases where the specific output type is not known (i.e. is an Object).
> Gh 2205 jsonserialiser

- core/store/src/main/java/uk/gov/gchq/gaffer/store/schema/Schema.java
- core/store/src/main/java/uk/gov/gchq/gaffer/store/schema/SchemaElementDefinitionValidator.java
- core/store/src/test/java/uk/gov/gchq/gaffer/store/schema/SchemaTest.java
> Gh 2432 schema merging error

- rest-api/spring-rest/src/main/java/uk/gov/gchq/gaffer/rest/controller/IOperationController.java
- rest-api/spring-rest/src/main/java/uk/gov/gchq/gaffer/rest/controller/OperationController.java
- rest-api/spring-rest/src/test/java/uk/gov/gchq/gaffer/rest/controller/OperationControllerTest.java
- rest-api/spring-rest/src/test/java/uk/gov/gchq/gaffer/rest/integration/controller/OperationControllerIT.java
> Added execute chunked endpoint to spring rest

- store-implementation/proxy-store/src/main/java/uk/gov/gchq/gaffer/proxystore/operation/GetProxyProperties.java
- store-implementation/proxy-store/src/main/java/uk/gov/gchq/gaffer/proxystore/operation/handler/GetProxyPropertiesHandler.java
- store-implementation/proxy-store/src/test/java/uk/gov/gchq/gaffer/proxystore/operation/GetProxyPropertiesTest.java
- store-implementation/proxy-store/src/test/java/uk/gov/gchq/gaffer/proxystore/operation/handler/GetProxyPropertiesHandlerTest.java
- store-implementation/proxy-store/src/test/java/uk/gov/gchq/gaffer/proxystore/operation/handler/GetUrlHandlerTest.java
> gh-2447 ProxyStore get proxy properties.

- core/store/src/main/java/uk/gov/gchq/gaffer/store/schema/Schema.java
- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreSchemaTest.java
> Allowed merging of schemas when one is a subset of another

- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/util/FederatedStoreUtil.java
- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/DoubleProxyTest.java
- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/SingleUseProxyMapStore.java
- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/operation/handler/FederatedOperationHandlerTest.java
- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/util/FederatedStoreUtilTest.java
- store-implementation/federated-store/src/test/resources/properties/singleUseMapStore.properties
> gh-2445 FederatedStore shallow clone options bug.

- core/operation/README.md
> Gh 2458 Update operation README with new sections

- .github/workflows/release.yaml
> gh-2471 Fix hotfix release merging issue

- pom.xml
> gh-2473 Increased sonatype release timeout to 15 mins

- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreSchemaTest.java
> gh-2462 Added federated schema merging aggregation tests

- store-implementation/federated-store/pom.xml
- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedGraphStorage.java
- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreCache.java
- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreCacheTest.java
- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/integration/AbstractStandaloneFederatedStoreIT.java
- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/integration/FederatedAdminIT.java
- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/integration/FederatedStoreRecursionIT.java
> gh-2435 federated store change graph id table name fix

- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedGraphStorage.java
- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/integration/AbstractStandaloneFederatedStoreIT.java
- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/integration/FederatedAdminIT.java
- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/integration/FederatedStoreRecursionIT.java
gh-2435 PR requests
- Resolve #2435
> gh-2435 federated store change graph id table name fix PR comments

- library/spark/spark-accumulo-library/src/test/java/uk/gov/gchq/gaffer/sparkaccumulo/integration/operation/handler/javaardd/SplitStoreFromJavaRDDOfElementsHandlerIT.java
For some reason this was not picked up by CI but broke locally when running all tests
- Resolve #2505
> gh-2505: Revert broken test to JUnit 4

- store-implementation/map-store/README.md
> gh-2510: Improved MapStore documentation

- integration-test/src/test/java/uk/gov/gchq/gaffer/integration/impl/GetElementsIT.java
- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreGetTraitsTest.java
> gh-2527: Fix potential GetElementsIT bug

- store-implementation/parquet-store/src/test/java/uk/gov/gchq/gaffer/parquetstore/operation/handler/AddElementsHandlerTest.java
- store-implementation/parquet-store/src/test/java/uk/gov/gchq/gaffer/parquetstore/utils/AggregateAndSortDataTest.java
- store-implementation/parquet-store/src/test/java/uk/gov/gchq/gaffer/parquetstore/utils/AggregateDataForGroupTest.java
- store-implementation/parquet-store/src/test/java/uk/gov/gchq/gaffer/parquetstore/utils/SortGroupSplitTest.java
- store-implementation/parquet-store/src/test/java/uk/gov/gchq/gaffer/parquetstore/utils/WriteUnsortedDataTest.java
> gh-2532: Remove log4j code uses

- .github/workflows/continuous-integration.yaml
> gh-2466: Ignore READMEs in CI

- .github/workflows/release-standalone.yaml
> gh-2543: Change release standalone jdk to v1

- .github/workflows/continuous-integration.yaml
> gh-2542: Add javadoc check to ci

- core/store/src/main/java/uk/gov/gchq/gaffer/store/Store.java
- core/store/src/main/java/uk/gov/gchq/gaffer/store/operation/HasTrait.java
- core/store/src/main/java/uk/gov/gchq/gaffer/store/operation/handler/HasTraitHandler.java
- core/store/src/test/java/uk/gov/gchq/gaffer/store/StoreTest.java
- core/store/src/test/java/uk/gov/gchq/gaffer/store/operation/HasTraitTest.java
- core/store/src/test/java/uk/gov/gchq/gaffer/store/operation/handler/HasTraitHandlerTest.java
> gh-2567: Cherry-picked HasTrait

- README.md
- core/graph/README.md
- core/operation/README.md
- core/store/src/main/java/uk/gov/gchq/gaffer/store/schema/SchemaOptimiser.java
- example/road-traffic/README.md
- rest-api/README.md
- rest-api/common-rest/src/main/java/uk/gov/gchq/gaffer/rest/SystemProperty.java
- store-implementation/accumulo-store/README.md
- store-implementation/accumulo-store/sample-files/store.properties.sample
- store-implementation/federated-store/README.md
- store-implementation/hbase-store/README.md
- store-implementation/parquet-store/README.md
Co-authored-by: t92549 <80890692+t92549@users.noreply.github.com>
- Resolve #2568
> gh-2568: Cherry-picked update links

- store-implementation/accumulo-store/src/main/java/uk/gov/gchq/gaffer/accumulostore/retriever/impl/AccumuloElementsRetriever.java
- store-implementation/accumulo-store/src/test/java/uk/gov/gchq/gaffer/accumulostore/integration/AccumuloMatchedVertexIT.java
> gh-2571: Fixed matchedVertex behaviour and added new ITs

- store-implementation/accumulo-store/src/main/java/uk/gov/gchq/gaffer/accumulostore/operation/handler/AddElementsHandler.java
Convert handlers to the new [Maestro](https://github.com/gchq/Maestro) format
- Resolve #2487
> Generic operation handler update

- README.md
- core/operation/README.md
- core/serialisation/src/main/java/uk/gov/gchq/gaffer/jsonserialisation/JSONSerialiser.java
- rest-api/common-rest/src/main/java/uk/gov/gchq/gaffer/rest/SystemProperty.java
- store-implementation/accumulo-store/README.md
> gh-2600: Update v2 README and docs links

- store-implementation/parquet-store/README.md
- store-implementation/parquet-store/src/main/java/uk/gov/gchq/gaffer/parquetstore/ParquetStore.java
> gh-2604: Deprecates Parquet

- library/cache-library/hazelcast-cache-service/pom.xml
- library/cache-library/hazelcast-cache-service/src/main/java/uk/gov/gchq/gaffer/cache/impl/HazelcastCache.java
- library/cache-library/hazelcast-cache-service/src/test/java/uk/gov/gchq/gaffer/cache/impl/HazelcastCacheTest.java
- library/cache-library/hazelcast-cache-service/src/test/resources/hazelcast.xml
> Upgrade Hazelcast version to 5.1.1

- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedGraphStorageTraitsTest.java
- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreGetTraitsTest.java
Cherry picked from https://github.com/gchq/Gaffer/pull/2583/commits/0788bc4790ae431f1862b7611255ab42778ee3eb
- Resolve #2616
> Cherry-pick federated traits test fix into develop

- store-implementation/accumulo-store/src/main/java/uk/gov/gchq/gaffer/accumulostore/operation/handler/GetElementsWithinSetHandler.java
- store-implementation/accumulo-store/src/main/java/uk/gov/gchq/gaffer/accumulostore/retriever/AccumuloSetRetriever.java
- store-implementation/accumulo-store/src/test/java/uk/gov/gchq/gaffer/accumulostore/operation/handler/GetElementsWithinSetHandlerTest.java
- store-implementation/accumulo-store/src/test/java/uk/gov/gchq/gaffer/accumulostore/retriever/impl/AccumuloIDWithinSetRetrieverTest.java
* Fixed bug gh-2562. View properties are now being filtered. Added tests
- Resolve #2620
> Gh-2620: Cherry-pick GetElementsWithinSet fix (#2597)

- core/common-util/src/main/java/uk/gov/gchq/gaffer/commonutil/ExecutorService.java
- core/data/src/main/java/uk/gov/gchq/gaffer/data/graph/Walk.java
- core/operation/src/test/java/uk/gov/gchq/gaffer/operation/impl/LimitTest.java
- core/operation/src/test/java/uk/gov/gchq/gaffer/operation/impl/output/ToArrayTest.java
- core/operation/src/test/java/uk/gov/gchq/gaffer/operation/impl/output/ToEntitySeedsTest.java
- core/operation/src/test/java/uk/gov/gchq/gaffer/operation/impl/output/ToListTest.java
- core/operation/src/test/java/uk/gov/gchq/gaffer/operation/impl/output/ToSetTest.java
- core/operation/src/test/java/uk/gov/gchq/gaffer/operation/impl/output/ToStreamTest.java
- core/serialisation/src/main/java/uk/gov/gchq/gaffer/serialisation/util/JsonSerialisationUtil.java
- core/serialisation/src/test/java/uk/gov/gchq/gaffer/serialisation/util/JsonSerialisationUtilTest.java
- core/store/src/test/java/uk/gov/gchq/gaffer/store/operation/handler/output/ToMapHandlerTest.java
- library/flink-library/pom.xml
- library/spark/pom.xml
- library/spark/spark-accumulo-library/pom.xml
- library/spark/spark-accumulo-library/src/main/java/uk/gov/gchq/gaffer/sparkaccumulo/operation/handler/javardd/GetJavaRDDOfAllElementsHandler.java
- library/spark/spark-accumulo-library/src/main/java/uk/gov/gchq/gaffer/sparkaccumulo/operation/handler/scalardd/GetRDDOfAllElementsHandler.java
- library/spark/spark-accumulo-library/src/main/java/uk/gov/gchq/gaffer/sparkaccumulo/operation/rfilereaderrdd/RFileReaderIterator.java
- pom.xml
- rest-api/common-rest/pom.xml
- store-implementation/accumulo-store/src/main/java/uk/gov/gchq/gaffer/accumulostore/operation/hdfs/handler/job/partitioner/GafferRangePartitioner.java
- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedAccess.java
- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/integration/FederatedAdminIT.java
> Gh-2300: Java 11 compatibility

- rest-api/spring-rest/pom.xml
- rest-api/spring-rest/src/test/java/uk/gov/gchq/gaffer/rest/integration/config/FactoryConfigIT.java
- rest-api/spring-rest/src/test/java/uk/gov/gchq/gaffer/rest/integration/config/JsonSerialisationConfigIT.java
- rest-api/spring-rest/src/test/java/uk/gov/gchq/gaffer/rest/integration/controller/AbstractRestApiIT.java
- rest-api/spring-rest/src/test/java/uk/gov/gchq/gaffer/rest/integration/controller/CorsIT.java
- rest-api/spring-rest/src/test/java/uk/gov/gchq/gaffer/rest/integration/controller/GraphConfigurationControllerIT.java
- rest-api/spring-rest/src/test/java/uk/gov/gchq/gaffer/rest/integration/controller/JobControllerIT.java
- rest-api/spring-rest/src/test/java/uk/gov/gchq/gaffer/rest/integration/controller/OperationControllerIT.java
- rest-api/spring-rest/src/test/java/uk/gov/gchq/gaffer/rest/integration/controller/PropertiesControllerIT.java
- rest-api/spring-rest/src/test/java/uk/gov/gchq/gaffer/rest/integration/controller/StatusControllerIT.java
- rest-api/spring-rest/src/test/java/uk/gov/gchq/gaffer/rest/integration/proxy/ProxyStoreIT.java
> Migrate spring-rest tests to use JUnit 5

- rest-api/spring-rest/pom.xml
> gh-2627: Upgrade spring-boot version to 2.5.12

- pom.xml
> gh-2640: Bump jackson version

- example/road-traffic/road-traffic-rest/src/test/java/uk.gov.gchq.gaffer.traffic/RoadTrafficTestQueries.java
- store-implementation/accumulo-store/src/test/java/uk/gov/gchq/gaffer/accumulostore/AccumuloStoreTest.java
- store-implementation/accumulo-store/src/test/java/uk/gov/gchq/gaffer/accumulostore/retriever/impl/AccumuloIDWithinSetRetrieverTest.java
- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreGetTraitsTest.java
- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreSchemaTest.java
- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreTest.java
- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreWrongGraphIDsTest.java
- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/operation/handler/impl/FederatedAddGraphHandlerTest.java
> Gh-2655: AssertJ withFailMessage order fix

- core/common-util/src/main/java/uk/gov/gchq/gaffer/commonutil/ExecutorService.java
- core/common-util/src/main/java/uk/gov/gchq/gaffer/commonutil/StreamUtil.java
- core/graph/src/main/java/uk/gov/gchq/gaffer/graph/Graph.java
- core/graph/src/main/java/uk/gov/gchq/gaffer/graph/hook/FunctionAuthoriser.java
- core/store/src/main/java/uk/gov/gchq/gaffer/store/operation/resolver/named/NamedOperationScoreResolver.java
- example/road-traffic/road-traffic-generators/src/main/java/uk/gov/gchq/gaffer/traffic/generator/RoadTrafficDataLoader.java
- library/cache-library/hazelcast-cache-service/src/main/java/uk/gov/gchq/gaffer/cache/impl/HazelcastCacheService.java
- library/hdfs-library/src/test/java/uk/gov/gchq/gaffer/hdfs/integration/loader/AddElementsFromHdfsLoaderIT.java
- library/spark/spark-accumulo-library/src/test/java/uk/gov/gchq/gaffer/sparkaccumulo/integration/operation/handler/scalardd/GetRDDOfAllElementsHandlerIT.java
- rest-api/accumulo-rest/src/test/java/uk/gov/gchq/gaffer/rest/factory/AccumuloDisableOperationsTest.java
- rest-api/spring-rest/src/main/java/uk/gov/gchq/gaffer/rest/controller/GraphConfigurationController.java
- store-implementation/accumulo-store/src/main/java/uk/gov/gchq/gaffer/accumulostore/operation/hdfs/handler/AddElementsFromHdfsHandler.java
- store-implementation/accumulo-store/src/main/java/uk/gov/gchq/gaffer/accumulostore/operation/hdfs/handler/job/factory/AccumuloAddElementsFromHdfsJobFactory.java
- store-implementation/accumulo-store/src/test/java/uk/gov/gchq/gaffer/accumulostore/operation/impl/CreateSplitPointsTest.java
- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedGraphStorage.java
- store-implementation/map-store/src/main/java/uk/gov/gchq/gaffer/mapstore/impl/AddElementsHandler.java
> gh-2657: Cherry-pick gh-2618: Cleanup inconsistent use of logging strings (#2651)

- NOTICES
- pom.xml
- rest-api/common-rest/src/main/resources/version.properties
> gh-2660: Update koryphe version to 2.4.0

- rest-api/core-rest/src/main/java/uk/gov/gchq/gaffer/rest/service/v2/GraphConfigurationServiceV2.java
- rest-api/core-rest/src/main/java/uk/gov/gchq/gaffer/rest/service/v2/IGraphConfigurationServiceV2.java
- rest-api/core-rest/src/test/java/uk/gov/gchq/gaffer/rest/service/v2/GraphConfigurationServiceV2Test.java
- rest-api/spring-rest/src/main/java/uk/gov/gchq/gaffer/rest/controller/GraphConfigurationController.java
- rest-api/spring-rest/src/main/java/uk/gov/gchq/gaffer/rest/controller/IGraphConfigurationController.java
- rest-api/spring-rest/src/test/java/uk/gov/gchq/gaffer/rest/controller/GraphConfigurationControllerTest.java
> Gh 2671 cherry pick aggregation endpoints

- core/data/README.md
> gh-2673: Fix links to koryphe core

- core/data/README.md
> gh-2673: Fix links to koryphe core (#2674)

- rest-api/spring-rest/src/main/java/uk/gov/gchq/gaffer/rest/controller/IOperationController.java
> gh-2683: Remove text from execute spring headers

- pom.xml
- rest-api/core-rest/pom.xml
- rest-api/spring-rest/pom.xml
The jersey version (2.25) has fallen a number of releases behind and needs upgrading.
- Resolve #2688
> Gh-2688 Upgrade to the latest jersey version (2.36).

- rest-api/common-rest/src/main/java/uk/gov/gchq/gaffer/rest/service/v2/AbstractOperationService.java
- rest-api/spring-rest/src/main/java/uk/gov/gchq/gaffer/rest/controller/IOperationController.java
- rest-api/spring-rest/src/main/java/uk/gov/gchq/gaffer/rest/controller/OperationController.java
> gh-2690: Add new operations/details/all endpoint to spring

- .github/workflows/continuous-integration.yaml
- example/basic/basic-rest/pom.xml
- example/federated-demo/pom.xml
- example/road-traffic/road-traffic-rest/pom.xml
- rest-api/core-rest/src/test/resources/junit-platform.properties
> Gh-2695: Unsilence CI output and fix timeout

- rest-api/spring-rest/src/test/java/uk/gov/gchq/gaffer/rest/controller/OperationControllerTest.java
> gh-2696: Added tests for new all operation details endpoint

- store-implementation/accumulo-store/src/main/java/uk/gov/gchq/gaffer/accumulostore/AccumuloProperties.java
- store-implementation/accumulo-store/src/main/java/uk/gov/gchq/gaffer/accumulostore/AccumuloStore.java
- store-implementation/accumulo-store/src/main/java/uk/gov/gchq/gaffer/accumulostore/utils/TableUtils.java
- store-implementation/accumulo-store/src/test/java/uk/gov/gchq/gaffer/accumulostore/AccumuloPropertiesTest.java
- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedGraphStorage.java
- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/integration/FederatedAdminIT.java
> Gh-2614: Enable alternative authentication to Accumulo using Kerberos

- README.md
Fixed Crown Copyright Link on Line 44
> Gh-2745: Fix crown copyright link

- core/operation/src/main/java/uk/gov/gchq/gaffer/operation/impl/export/localfile/ExportToLocalFile.java
- core/operation/src/main/java/uk/gov/gchq/gaffer/operation/io/Output.java
- core/operation/src/test/java/uk/gov/gchq/gaffer/operation/export/localfile/ExportToLocalFileTest.java
- rest-api/common-rest/src/main/java/uk/gov/gchq/gaffer/rest/model/OperationDetail.java
- rest-api/spring-rest/src/test/java/uk/gov/gchq/gaffer/rest/integration/controller/OperationControllerIT.java
> Gh 2755 fix operation output type

- core/store/src/test/java/uk/gov/gchq/gaffer/store/operation/handler/named/cache/NamedOperationCacheBackwardCompatibilityTest.java
- core/store/src/test/java/uk/gov/gchq/gaffer/store/operation/handler/named/cache/NamedViewCacheBackwardCompatibilityTest.java
- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreCacheBackwardCompatibilityTest.java
> Added comments in tests where cache is populated from file

- store-implementation/accumulo-store/src/test/resources/log4j.xml
- store-implementation/federated-store/src/test/resources/log4j.xml
> Gh-2786: Filter test logs to remove unnecessary information

- core/graph/src/main/java/uk/gov/gchq/gaffer/operation/export/graph/handler/GraphDelegate.java
- core/store/src/main/java/uk/gov/gchq/gaffer/store/library/GraphLibrary.java
- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreGraphVisibilityTest.java
> gh-2809 federatedstore fix incorrect test refracting

- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/util/FederatedStoreUtil.java
- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreGraphIDsTest.java
> Gh-2773: Tests to document deprecated graphId behaviour

- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedStore.java
- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreTest.java
> Gh-2784: Add comments that explain graphId order

- core/operation/src/main/java/uk/gov/gchq/gaffer/operation/impl/output/ToCsv.java
- core/operation/src/test/java/uk/gov/gchq/gaffer/operation/impl/output/ToCsvTest.java
- core/store/src/main/java/uk/gov/gchq/gaffer/store/operation/handler/output/ToCsvHandler.java
- rest-api/common-rest/src/main/java/uk/gov/gchq/gaffer/rest/factory/AbstractExamplesFactory.java
> gh-2843: Fix operation examples, revert ToCsv field rename

- core/store/src/main/java/uk/gov/gchq/gaffer/store/Store.java
- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedStore.java
- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/operation/handler/FederatedAddGraphHandlerParent.java
- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/operation/handler/impl/FederatedRemoveGraphHandler.java
- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreTest.java
> Gh-2779: FederatedStore remove handlers on RemoveGraph

- library/spark/spark-accumulo-library/src/test/java/uk/gov/gchq/gaffer/sparkaccumulo/operation/handler/javardd/ImportJavaRDDOfElementsHandlerTest.java
- library/spark/spark-accumulo-library/src/test/java/uk/gov/gchq/gaffer/sparkaccumulo/operation/handler/javardd/ImportKeyValueJavaPairRDDToAccumuloHandlerTest.java
- library/spark/spark-accumulo-library/src/test/java/uk/gov/gchq/gaffer/sparkaccumulo/operation/handler/scalardd/ImportRDDOfElementsHandlerTest.java
- store-implementation/proxy-store/src/test/java/uk/gov/gchq/gaffer/proxystore/integration/ProxyStoreBasicIT.java
- store-implementation/proxy-store/src/test/java/uk/gov/gchq/gaffer/proxystore/integration/ProxyStoreITs.java
- store-implementation/proxy-store/src/test/java/uk/gov/gchq/gaffer/proxystore/integration/ProxyStoreResponseDeserialiserIT.java
Also includes a fix to cleanup method in associated ITs which wasn't working correctly.
- Resolve #2849
> Gh-2849: Fix JUnit @TempDir annotation

- library/cache-library/hazelcast-cache-service/pom.xml
> Cherry-pick bump hazelcast 5.1.3

- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedStore.java
> gh-2859 revert typo of typo

- pom.xml
> Gh-2850: Fix failsafe plugin skipping some ITs

- core/store/src/main/java/uk/gov/gchq/gaffer/store/operation/handler/output/ToCsvHandler.java
- core/store/src/test/java/uk/gov/gchq/gaffer/store/operation/handler/output/ToCsvHandlerTest.java
- integration-test/src/main/java/uk/gov/gchq/gaffer/integration/impl/ImportExportIT.java
> Gh-2858: Fix ImportExportIT and ToCsvHandler

- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/operation/handler/impl/FederatedOperationHandler.java
- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/util/FederatedStoreUtil.java
- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/util/FederatedStoreUtilTest.java
> Gh 2875 federated store federated operation handler loosing inputs

- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/util/FederatedStoreUtil.java
> Gh-2877: Use full path for storeConfigured configs files

- core/store/src/test/java/uk/gov/gchq/gaffer/store/schema/SchemaEdgeDefinitionTest.java
- core/store/src/test/java/uk/gov/gchq/gaffer/store/schema/SchemaElementDefinitionTest.java
- core/store/src/test/java/uk/gov/gchq/gaffer/store/schema/SchemaEntityDefinitionTest.java
> Add tests to ensure element definition orders

- core/graph/src/main/java/uk/gov/gchq/gaffer/graph/Graph.java
- core/store/src/main/java/uk/gov/gchq/gaffer/store/Store.java
- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedStore.java
- store-implementation/proxy-store/src/main/java/uk/gov/gchq/gaffer/proxystore/ProxyStore.java
> Gh-2882: Improve getSchema Javadoc and remove deprecation

- core/store/src/main/java/uk/gov/gchq/gaffer/store/StoreTrait.java
- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/operation/FederatedOperationChainValidator.java
- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/util/FederatedStoreUtil.java
- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/integration/FederatedStoreRecursionIT.java
> Gh-2580: Remove DYNAMIC_SCHEMA Trait and usages

- store-implementation/proxy-store/src/main/java/uk/gov/gchq/gaffer/proxystore/ProxyStore.java
> Gh-2917: ProxyStore dynamic GetTraits handler

- core/operation/src/main/java/uk/gov/gchq/gaffer/jobtracker/JobTracker.java
- core/store/src/main/java/uk/gov/gchq/gaffer/store/StoreProperties.java
- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedStore.java
- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreCacheTransient.java
- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreMultiCacheTest.java
- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreTest.java
- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreTestUtil.java
- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/integration/FederatedAdminIT.java
> gh-2886 FederatedStore remove double caching accidental collision.

- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreProperties.java
- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/operation/handler/FederatedAddGraphHandlerParent.java
> Gh 2890 cache service static instance bug

- core/cache/src/main/java/uk/gov/gchq/gaffer/cache/Cache.java
- core/operation/src/main/java/uk/gov/gchq/gaffer/jobtracker/JobTracker.java
- core/operation/src/main/java/uk/gov/gchq/gaffer/named/operation/NamedOperationDetail.java
- core/store/src/main/java/uk/gov/gchq/gaffer/store/operation/handler/named/cache/NamedOperationCache.java
- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreCache.java
> gh-2865 Cache Exceptions usage and review

- NOTICES
- pom.xml
- rest-api/common-rest/src/main/resources/version.properties
> Gh-2933: Upgrade Koryphe version

- library/cache-library/hazelcast-cache-service/pom.xml
- library/flink-library/pom.xml
- pom.xml
> Gh-2949: Update dependency versions ahead of Gaffer 2.0.0 release

- .github/workflows/continuous-integration.yaml
> Gh-2713: Move to codecov app and action v3

- pom.xml
> Gh-2956: Update Maven Dependency plugins

- README.md
- pom.xml
> Gh-2954: Remove mentions of v2-alpha

- .github/workflows/codeql.yaml
- .github/workflows/create-hotfix-branch.yaml
- .github/workflows/create-release-branch.yaml
- .github/workflows/release-standalone.yaml
- .github/workflows/release.yaml
- .github/workflows/update-koryphe-version.yaml
> Gh-2960: Git user shows as invalid for commits made by GitHub Actions

- store-implementation/proxy-store/src/main/java/uk/gov/gchq/gaffer/proxystore/ProxyStore.java
> Gh-3001: Document getGetTraitsHandler in ProxyStore

- rest-api/common-rest/src/main/java/uk/gov/gchq/gaffer/rest/service/v2/AbstractOperationService.java
- rest-api/spring-rest/src/main/java/uk/gov/gchq/gaffer/rest/controller/IOperationController.java
- rest-api/spring-rest/src/main/java/uk/gov/gchq/gaffer/rest/controller/OperationController.java
- rest-api/spring-rest/src/test/java/uk/gov/gchq/gaffer/rest/controller/OperationControllerTest.java
New "/graph/operations/all" endpoint for retrieving sorted operation names.
> Gh-2836: New operation names endpoint

- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedStore.java
- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreProperties.java
FederatedStore tech debt consolidation of constructor and StoreProperties for configuring.
> FederatedStore tech debt

- rest-api/common-rest/src/main/java/uk/gov/gchq/gaffer/rest/factory/AbstractExamplesFactory.java
- rest-api/common-rest/src/test/java/uk/gov/gchq/gaffer/rest/factory/AbstractExamplesFactoryTest.java
- rest-api/common-rest/src/test/resources/schema/schemaNoEdges.json
- rest-api/common-rest/src/test/resources/schema/schemaNoEntities.json
> Gh-3046: Fix spring-rest to allow schema with no entities

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/release-notes.yml
- core/common-util/src/test/java/uk/gov/gchq/gaffer/commonutil/ByteBufferUtilTest.java
> Gh-3041: Added support for feature label

- core/store/src/test/java/uk/gov/gchq/gaffer/store/TestTypes.java
- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreVisibilityTest.java
> Gh-3042: Tidy FederatedStoreVisibilityTest

- store-implementation/accumulo-store/src/test/java/uk/gov/gchq/gaffer/accumulostore/integration/AccumuloMatchedVertexIT.java
Small tidy up identified when doing https://github.com/gchq/gaffer-doc/pull/431
- Resolve #3039
> Gh-3039: Tidy AccumuloMatchedVertexIT

- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/operation/FederatedOperation.java
- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreGetWalksTest.java
> Gh-3054: GetWalks now works with FederatedOperation, added test

- .github/workflows/continuous-integration.yaml
> Gh-3081: Add CodeCov token

- library/sketches-library/src/main/java/uk/gov/gchq/gaffer/sketches/CardinalityEntityGenerator.java
- library/sketches-library/src/main/java/uk/gov/gchq/gaffer/sketches/datasketches/cardinality/function/IterableToHllSketch.java
- library/sketches-library/src/main/java/uk/gov/gchq/gaffer/sketches/datasketches/cardinality/function/ToHllSketch.java
- library/sketches-library/src/test/java/uk/gov/gchq/gaffer/sketches/datasketches/cardinality/function/IterableToHllSketchTest.java
- library/sketches-library/src/test/java/uk/gov/gchq/gaffer/sketches/datasketches/cardinality/function/ToHllSketchTest.java
> Gh-3061: Ensure ToHllSketch functions copy

- library/tinkerpop/src/main/java/uk/gov/gchq/gaffer/tinkerpop/GafferPopGraphFeatures.java
- library/tinkerpop/src/test/java/uk/gov/gchq/gaffer/tinkerpop/GafferPopGraphFeaturesTest.java
> Gh-3080: Add testing for GafferPopGraphFeatures

- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreSchemaOverlapTest.java
> Gh-3114: Add test for FederatedStoreSchemaOverlapTest different serialiser

- library/tinkerpop/src/test/java/uk/gov/gchq/gaffer/tinkerpop/GafferPopGremlinPluginTest.java
Add unit testing to the GafferPopGremlinPlugin to improve Gremlin coverage.
- Resolve #3112
> Gh-3112: Improve GafferPopGremlinPlugin testing

- .github/workflows/create-release-branch.yaml
> Gh-3113: Fix regex in create release branch workflow

- library/tinkerpop/src/test/java/uk/gov/gchq/gaffer/tinkerpop/GafferPopGraphIT.java
- library/tinkerpop/src/test/java/uk/gov/gchq/gaffer/tinkerpop/service/GafferPopNamedOperationServiceIT.java
- library/tinkerpop/src/test/java/uk/gov/gchq/gaffer/tinkerpop/util/GafferPopTestUtil.java
> Gh-3107: Refactor GafferPopGraphTest to an IT and separate util methods

- library/tinkerpop/src/main/java/uk/gov/gchq/gaffer/tinkerpop/GafferPopGraph.java
- library/tinkerpop/src/test/java/uk/gov/gchq/gaffer/tinkerpop/GafferPopGraphIT.java
- library/tinkerpop/src/test/java/uk/gov/gchq/gaffer/tinkerpop/GafferPopGraphTest.java
Changed the try/catch to catch all exceptions and added a test that it catches any invalid operation chains.
> Gh-3125: GafferPopGraph should catch certain exceptions

- core/store/pom.xml
> Gh-3141: Fix store tests JUnit classloader error

- core/data/src/main/java/uk/gov/gchq/gaffer/data/elementdefinition/view/View.java
- core/data/src/test/java/uk/gov/gchq/gaffer/data/elementdefinition/view/ViewTest.java
- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/util/FederatedStoreUtil.java
- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/util/MergeElementFunction.java
- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/util/MergeSchema.java
- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/util/MergeElementFunctionTest.java
> Gh 3059 pr refactor

- core/graph/src/test/java/uk/gov/gchq/gaffer/integration/operation/named/cache/NamedOperationCacheIT.java
> Gh-3171: Refactor NamedOperationCacheIT

- example/road-traffic/road-traffic-demo/pom.xml
Tested locally
- Resolve #3185
> Gh-3185: Road traffic demo REST port is not changed by POM property

- .gitpod.yml
- README.md
> Gh-3192: Improve README and GitPod config

- .github/workflows/continuous-integration.yaml
> Gh-3196: Actions Javadoc Java versions inconsistent

- store-implementation/accumulo-store/src/main/java/uk/gov/gchq/gaffer/accumulostore/AccumuloStore.java
- store-implementation/accumulo-store/src/main/java/uk/gov/gchq/gaffer/accumulostore/utils/TableUtils.java
- store-implementation/accumulo-store/src/test/java/uk/gov/gchq/gaffer/accumulostore/utils/TableUtilsTest.java
- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedGraphStorage.java
- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/operation/handler/impl/FederatedChangeGraphIdHandlerTest.java
> Gh-2495: FederatedGraphStorage has Accumulo specific code

- core/store/src/main/java/uk/gov/gchq/gaffer/store/Store.java
- core/store/src/main/java/uk/gov/gchq/gaffer/store/StoreProperties.java
- core/store/src/test/java/uk/gov/gchq/gaffer/store/StorePropertiesTest.java
- core/store/src/test/java/uk/gov/gchq/gaffer/store/StoreTest.java
- core/store/src/test/java/uk/gov/gchq/gaffer/store/integration/StoreIT.java
> Gh-3169: Add config options to disable named operations and named views

- .github/workflows/release.yaml
> Gh-3212: Upgrade Release GitHub Action version

- library/tinkerpop/src/main/java/uk/gov/gchq/gaffer/tinkerpop/process/traversal/step/GafferPopGraphStep.java
- library/tinkerpop/src/test/java/uk/gov/gchq/gaffer/tinkerpop/process/traversal/step/GafferPopHasStepIT.java
> Gh-3226: handle empty hasId input

- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/operation/FederatedOperation.java
- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/operation/FederatedOperationTest.java
> Gh-3085 Fix payloadOperation being exposed by getOperations

- NOTICES
- core/store/src/test/java/uk/gov/gchq/gaffer/store/operation/handler/MapHandlerTest.java
- pom.xml
> Gh-3368: Update Koryphe version
