gchq/Gaffer

- accumulo-store/src/main/java/gaffer/accumulostore/AccumuloProperties.java
- accumulo-store/src/main/java/gaffer/accumulostore/utils/TableUtils.java
See Issue G32,
Adding a property so that users can over-ride accumulo default settings for table file replication per table if desired.
> G32 add replication property

- accumulo-store/src/main/java/gaffer/accumulostore/operation/hdfs/handler/AddElementsFromHdfsHandler.java
- accumulo-store/src/main/java/gaffer/accumulostore/operation/hdfs/handler/ImportAccumuloKeyValueFilesHandler.java
- accumulo-store/src/main/java/gaffer/accumulostore/operation/hdfs/handler/tool/ImportElementsToAccumulo.java
- accumulo-store/src/main/java/gaffer/accumulostore/operation/hdfs/impl/ImportAccumuloKeyValueFiles.java
- accumulo-store/src/main/java/gaffer/accumulostore/operation/hdfs/impl/SampleDataForSplitPoints.java
- accumulo-store/src/main/java/gaffer/accumulostore/utils/AccumuloStoreConstants.java
- simple-operation-library/src/main/java/gaffer/operation/simple/hdfs/AddElementsFromHdfs.java
- simple-operation-library/src/main/java/gaffer/operation/simple/hdfs/MapReduceOperation.java
Added Option & AccumuloStoreConstant to skip import step on AddElementsFromHdfs for the accumulo-store
Added Operation to do the import of keys/values to Accumulo from a directory.
Moved failureDirectory path variable from MapReduceOperation to AddElementsFromHdfs & ImportKeyValueFiles.
> gh-98 Enable AccumuloStore Import step to be run in two parts

- example/pom.xml
This means any of the examples can be run by supplying the class name on the command line, e.g:
java -cp example-jar-with-dependencies.jar gaffer.example.gettingstarted.analytic.LoadAndQuery1
> gh-201 - removed main class from example jar manifest

- accumulo-store/src/main/java/gaffer/accumulostore/operation/hdfs/handler/job/SampleDataForSplitPointsJobFactory.java
- accumulo-store/src/main/java/gaffer/accumulostore/operation/hdfs/impl/SampleDataForSplitPoints.java
- accumulo-store/src/test/java/gaffer/accumulostore/operation/hdfs/impl/SampleDataForSplitPointsTest.java
Remove the ability to set the number of reducers and the partitioner from the Operation Builder and if set on the operation class it will result in an IllegalArgumentException
The Job Factory for this operation will now also always set the reducers to 1, as required for the operation to function correctly.
> gh-310 Refactor SampleDataForSplitPoints operation

- example-rest/src/main/webapp/WEB-INF/web.xml
This sometimes caused conflicts when using the embedded jetty server. Due to this the python example sometimes didn't work.
> gh-397 - tidied up web.xml for example rest api

- NOTICES
- core/common-util/pom.xml
- core/common-util/src/main/java/gaffer/commonutil/CommonTimeUtil.java
- core/common-util/src/test/java/gaffer/commonutil/CommonTimeUtilTest.java
Started the CommonTimeUtils class with a rough method for creating buckets of time from long timestamps.
The joda-time library has been added and replaces the functionality that was in the Gaffer1 TimeUtils class.
> gh-444 - Added CommonTimeUtil class

- library/bitmap-library/pom.xml
- library/bitmap-library/src/main/java/uk/gov/gchq/gaffer/bitmap/function/aggregate/RoaringBitmapAggregator.java
- library/bitmap-library/src/main/java/uk/gov/gchq/gaffer/bitmap/serialisation/RoaringBitmapSerialiser.java
- library/bitmap-library/src/main/java/uk/gov/gchq/gaffer/bitmap/serialisation/json/RoaringBitmapConstants.java
- library/bitmap-library/src/main/java/uk/gov/gchq/gaffer/bitmap/serialisation/json/RoaringBitmapJsonDeserialiser.java
- library/bitmap-library/src/main/java/uk/gov/gchq/gaffer/bitmap/serialisation/json/RoaringBitmapJsonSerialiser.java
- library/bitmap-library/src/main/java/uk/gov/gchq/gaffer/bitmap/serialisation/utils/RoaringBitmapUtils.java
- library/bitmap-library/src/test/java/uk/gov/gchq/gaffer/bitmap/function/aggregate/RoaringBitmapAggregatorTest.java
- library/bitmap-library/src/test/java/uk/gov/gchq/gaffer/bitmap/serialisation/RoaringBitmapSerialiserTest.java
- library/bitmap-library/src/test/java/uk/gov/gchq/gaffer/bitmap/serialisation/json/RoaringBitmapJsonSerialisationTest.java
- library/sketches-library/pom.xml
Change package to have uk.gov.gchq prefix and add a RoaringBitmap aggregation function.
Adding shaded "deploy" jars build instructions to the pom of the bitmap and sketches library, so these can be used alongside core gaffer without other dependencies.
> gh-702 RoaringBitmap aggregation function

- core/graph/src/main/java/uk/gov/gchq/gaffer/operation/export/graph/handler/ExportToOtherGraphHandler.java
ExportToOtherGraphHandler#createGraph
potentially the method fields could be removed and the inner three methods be simply passed export & store. this would be in keeping with the clean practice of small method parameter volume.
> Gh 287 refactor export to other graph handler

- core/store/src/main/java/uk/gov/gchq/gaffer/store/schema/SchemaElementDefinition.java
- store-implementation/parquet-store/src/test/java/uk/gov/gchq/gaffer/parquetstore/utils/ParquetFileIteratorTest.java
Removed expectation of a specific order of the paths provided in the ParquetFileIteratorTest
Small checkstyle issue fixed to ensure project builds successfully.
> Gh-1156 - Parquet test unordering

- store-implementation/accumulo-store/src/main/java/uk/gov/gchq/gaffer/accumulostore/key/core/AbstractCoreKeyRangeFactory.java
- store-implementation/accumulo-store/src/main/java/uk/gov/gchq/gaffer/accumulostore/key/core/impl/byteEntity/ByteEntityRangeFactory.java
- store-implementation/accumulo-store/src/main/java/uk/gov/gchq/gaffer/accumulostore/key/core/impl/classic/ClassicRangeFactory.java
- store-implementation/accumulo-store/src/test/java/uk/gov/gchq/gaffer/accumulostore/integration/GetElementsInRangesIT.java
It is not perfect, but at least the 2 key packages now return the same results.
The change only affects the classic key package, as the byte entity package seemed to be returning the correct results. When the ranges are constructed, the incoming/outgoing flag is now ignored, but it is still used in an iterator to filter out any edges that are the wrong way around.
> gh-1124 - disabled in out flag for edge ids in get ranges

- core/store/README.md
store/README.md now correctly details how a ScoreOperationChain should be declared for use.
> gh-1364 - Updated readme with up-to-date info

- core/data/src/main/java/uk/gov/gchq/gaffer/data/element/Edge.java
- rest-api/core-rest/src/main/java/uk/gov/gchq/gaffer/rest/service/v2/GraphConfigurationServiceV2.java
- rest-api/core-rest/src/main/java/uk/gov/gchq/gaffer/rest/service/v2/IGraphConfigurationServiceV2.java
- rest-api/core-rest/src/test/java/uk/gov/gchq/gaffer/rest/service/v2/GraphConfigurationServiceV2Test.java
The GetSerialisedFields endpoint now returns a Map of Serialised Field to corresponding class type.
Any unknown enums are described as a String, since (de)serialisation will handle this.
The full qualified class name is also included.
> Gh-1624 Class Info for GetSerialisedFields

- core/store/src/main/java/uk/gov/gchq/gaffer/store/operation/handler/ScoreOperationChainHandler.java
- core/store/src/test/java/uk/gov/gchq/gaffer/store/operation/handler/ScoreOperationChainHandlerTest.java
Any implementations of ScoreResolver which are native to Gaffer are now added to the list of available ScoreResolvers by default. 
This can easily be expanded as and when any new implementations are added, but still allows for externally configurable resolvers to be added via a json config file.
> gh-1672 - Register Default ScoreResolver implementations

- core/operation/src/main/java/uk/gov/gchq/gaffer/operation/impl/Reduce.java
- core/operation/src/test/java/uk/gov/gchq/gaffer/operation/impl/function/ReduceTest.java
- core/store/src/main/java/uk/gov/gchq/gaffer/store/Store.java
- core/store/src/main/java/uk/gov/gchq/gaffer/store/operation/handler/ReduceHandler.java
- core/store/src/test/java/uk/gov/gchq/gaffer/store/StoreTest.java
- core/store/src/test/java/uk/gov/gchq/gaffer/store/operation/handler/ReduceHandlerTest.java
A simple implementation of a `Reduce` operation which should be compatible with the existing Koryphe `BinaryOperator` classes.
There's an issue with generic invariance on the Java 8 implementation of the `Stream#reduce(BinaryOperator<T> binaryOperator)` method.
A workaround is to "coerce" the types of objects in the stream into the target type by using the three argument `reduce(U identity, BiFunction<U,? super T,U> accumulator, BinaryOperator<U> combiner)` method.
I can provide more examples of the `Reduce` operation as an integration test if that would be helpful.
The `@Since` annotations will also need to be updated, depending on your release schedule.
> gh-1859 - Implement a Reduce operation.

- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedStore.java
- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreTest.java
Removed unnecessary override of method
It is already implemented correctly in Super Class of FederatedStore.java i.e. Store.java
> gh-2209: Improve error message for unsupported operations in the federated store

- store-implementation/proxy-store/src/main/java/uk/gov/gchq/gaffer/proxystore/ProxyStore.java
ProxyStore get status typo, key is status not description.
> ProxyStore get status typo

- core/operation/src/main/java/uk/gov/gchq/gaffer/named/operation/AddNamedOperation.java
- core/operation/src/main/java/uk/gov/gchq/gaffer/named/operation/NamedOperationDetail.java
- core/operation/src/test/java/uk/gov/gchq/gaffer/named/operation/AddNamedOperationTest.java
- core/store/src/main/java/uk/gov/gchq/gaffer/store/operation/handler/named/AddNamedOperationHandler.java
- core/store/src/test/java/uk/gov/gchq/gaffer/store/operation/handler/named/AddNamedOperationHandlerTest.java
- core/store/src/test/java/uk/gov/gchq/gaffer/store/operation/handler/named/GetAllNamedOperationsHandlerTest.java
- integration-test/src/test/java/uk/gov/gchq/gaffer/integration/impl/GraphHooksIT.java
- rest-api/core-rest/src/main/java/uk/gov/gchq/gaffer/rest/service/v2/example/DefaultExamplesFactory.java
- rest-api/core-rest/src/main/java/uk/gov/gchq/gaffer/rest/service/v2/example/ExamplesFactory.java
- rest-api/core-rest/src/test/java/uk/gov/gchq/gaffer/rest/service/impl/OperationServiceIT.java
- rest-api/core-rest/src/test/java/uk/gov/gchq/gaffer/rest/service/v2/OperationServiceV2IT.java
Hi - here is the back end change for Issue #791 (in gaffer-tools) - it's ready to go in to develop anytime by itself.
This backend feature in this PR is just enabling NamedOperationDetail to include a label and it is safe to merge anytime - as I'm still working on the gaffer-tools UI to send the request down.
It is compatible with the current request that gaffer-tools and Swagger sends (i.e. it sends AddNamedOperation request with "label" missing from body - the backend will read this as null).
Let me know what you think, thanks
> Gh 791 add named operation group label (part of tools Issue #791)

- core/data/src/main/java/uk/gov/gchq/gaffer/data/elementdefinition/view/View.java
- core/graph/src/main/java/uk/gov/gchq/gaffer/graph/Graph.java
- core/graph/src/test/java/uk/gov/gchq/gaffer/graph/GraphTest.java
- store-implementation/federated-store/pom.xml
- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/operation/handler/FederatedOperationHandlerTest.java
- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/operation/handler/impl/FederatedOperationChainHandlerTest.java
Resolves #2293 
Only expand Global* elements in a View if the schema contains an entry with that element type in.  This supports stores such as the FederatedStore where the first Store a query gets run against is in some way a proxy of some other store(s) and doesn't have the schema information to do the expansion.
Also, update the logic in updateOperationChain such that it no longer expands  a View with no entities and edges but, e.g., a globalEntities element to include all of the edges.
When reviewing, please note that I've chosen to change updateOperationChain to default scope for testing purposes and because the code didn't feel like it was perfectly encapsulated by the logic of executing a query.  Alternatively, I could change the tests to run against the public execute method …
> bugfix for gh-2239:  Merging views with global elements

- example/basic/basic-rest/pom.xml
- example/road-traffic/road-traffic-demo/pom.xml
- example/road-traffic/road-traffic-rest/src/main/java/uk/gov/gchq/gaffer/traffic/listeners/ConsoleBanner.java
- example/road-traffic/road-traffic-rest/src/main/resources/log4j.xml
- example/road-traffic/road-traffic-rest/src/main/webapp/WEB-INF/web.xml
- Added listener which writes a message to the console once the application is ready
- Exposed the port as a system property so that a valid hyperlink can be included in the log message
- Suppressed some debug messages from Swagger to make it easier to see the "ready" message
> gh-2284 Add dynamic message to log after road-traffic example starts.

- .github/workflows/release.yaml
- .github/workflows/release_standalone.yaml
Also removed use of `.m2/repository` cache as it is unused in a release
- Resolve #2468
> Added hotfix check that skips merge develop

- rest-api/spring-rest/pom.xml
The spring boot maven plugin did not have a version set.
https://github.com/gchq/Gaffer/blob/b22d7a7ab1974399edad87f6f7962b2aa5b6f4f6/rest-api/spring-rest/pom.xml#L135-L138
This had been causing unnoticed build warnings about build stability: 
```
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for uk.gov.gchq.gaffer:spring-rest:jar:1.17.1-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.springframework.boot:spring-boot-maven-plugin is missing. @ line 135, column 15
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] …
```
> gh-2463 Added version number to spring boot maven plugin

- core/graph/src/test/java/uk/gov/gchq/gaffer/integration/operation/named/cache/NamedOperationCacheIT.java
- core/operation/src/main/java/uk/gov/gchq/gaffer/named/operation/AddNamedOperation.java
- core/operation/src/test/java/uk/gov/gchq/gaffer/named/operation/AddNamedOperationTest.java
- core/store/src/test/java/uk/gov/gchq/gaffer/store/operation/handler/named/GetAllNamedOperationsHandlerTest.java
- rest-api/core-rest/src/test/java/uk/gov/gchq/gaffer/rest/service/impl/OperationServiceIT.java
Read and Write access role properties are mutually exclusive with read and write AccessPredicate properties.
Also added some @Test annotations (see #2452) and corrected the tests which were broken and now executing again.
> gh-2476 Stop defaulting access roles to empty arrays. 

- core/data/src/test/java/uk/gov/gchq/gaffer/integration/ViewIT.java
- core/graph/src/test/java/uk/gov/gchq/gaffer/integration/graph/GraphIT.java
- core/graph/src/test/java/uk/gov/gchq/gaffer/integration/graph/SchemaHidingIT.java
- core/graph/src/test/java/uk/gov/gchq/gaffer/integration/operation/named/cache/NamedOperationCacheIT.java
- core/store/src/test/java/uk/gov/gchq/gaffer/store/operation/handler/named/cache/NamedViewCacheBackwardCompatibilityTest.java
- library/flink-library/src/test/java/uk/gov/gchq/gaffer/flink/integration/operation/handler/AddElementsFromFileHandlerIT.java
- library/flink-library/src/test/java/uk/gov/gchq/gaffer/flink/integration/operation/handler/AddElementsFromKafkaHandlerIT.java
- library/flink-library/src/test/java/uk/gov/gchq/gaffer/flink/integration/operation/handler/AddElementsFromSocketHandlerIT.java
- library/flink-library/src/test/java/uk/gov/gchq/gaffer/flink/operation/FlinkTest.java
- library/spark/spark-accumulo-library/src/test/java/uk/gov/gchq/gaffer/sparkaccumulo/integration/operation/handler/javaardd/SplitStoreFromJavaRDDOfElementsHandlerIT.java
- library/spark/spark-accumulo-library/src/test/java/uk/gov/gchq/gaffer/sparkaccumulo/integration/operation/handler/scalardd/SplitStoreFromRDDOfElementsHandlerIT.java
- rest-api/core-rest/src/test/java/uk/gov/gchq/gaffer/rest/RestApiTestClient.java
- rest-api/core-rest/src/test/java/uk/gov/gchq/gaffer/rest/service/v1/OperationServiceV1IT.java
- store-implementation/accumulo-store/src/test/java/uk/gov/gchq/gaffer/accumulostore/integration/AccumuloAggregationIT.java
- store-implementation/accumulo-store/src/test/java/uk/gov/gchq/gaffer/accumulostore/integration/GetElementsInRangesIT.java
- store-implementation/accumulo-store/src/test/java/uk/gov/gchq/gaffer/accumulostore/integration/delete/AbstractDeletedElementsIT.java
- store-implementation/accumulo-store/src/test/java/uk/gov/gchq/gaffer/accumulostore/integration/performance/BloomFilterIT.java
- store-implementation/accumulo-store/src/test/java/uk/gov/gchq/gaffer/accumulostore/operation/impl/CreateSplitPointsTest.java
- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/DoubleProxyTest.java
- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreToFederatedStoreTest.java
- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/integration/FederatedStoreRecursionIT.java
- store-implementation/hbase-store/src/test/java/uk/gov/gchq/gaffer/hbasestore/serialisation/LazyElementCellTest.java
- store-implementation/proxy-store/src/test/java/uk/gov/gchq/gaffer/proxystore/SingleUseProxyStore.java
- store-implementation/proxy-store/src/test/java/uk/gov/gchq/gaffer/proxystore/integration/ProxyStoreBasicIT.java
- store-implementation/proxy-store/src/test/java/uk/gov/gchq/gaffer/proxystore/integration/ProxyStoreResponseDeserialiserIT.java
This PR should remove all usages of JUnit4 that aren't to do with either store integration tests or spring rest tests.
Particular points of interest are [RestApiTestClient](https://github.com/gchq/Gaffer/blob/c7028e7f9c9f363959b7e19f4f1b477e88aafb29/rest-api/core-rest/src/test/java/uk/gov/gchq/gaffer/rest/RestApiTestClient.java) and [FlinkTest](https://github.com/gchq/Gaffer/blob/c7028e7f9c9f363959b7e19f4f1b477e88aafb29/library/flink-library/src/test/java/uk/gov/gchq/gaffer/flink/operation/FlinkTest.java) which had to be cleaned up and I would like confirming that the clean up was okay.
- Resolve #2499
> gh-2499: Upgraded miscellaneous tests to JUnit 5

- store-implementation/accumulo-store/src/test/java/uk/gov/gchq/gaffer/accumulostore/key/core/impl/bytedEntity/ByteEntityAccumuloElementConverterTest.java
- store-implementation/accumulo-store/src/test/java/uk/gov/gchq/gaffer/accumulostore/key/core/impl/bytedEntity/ByteEntityAccumuloElementConverterVisibilityTest.java
- store-implementation/accumulo-store/src/test/resources/schemaWithVisibilities/types.json
Added a new test class that is a subclass of ByteEntityAccumuloElementConverterTest, with the only changes being that it uses the visibility schema and so expects an extra serialised property. 
There is also a new test which creates a serialised Properties from the full column qualifier, rather than just the first two properties.
- Resolve #2488
> gh-2488: Added ByteEntityAccumuloElementConverter visibility tests

- integration-test/src/test/java/uk/gov/gchq/gaffer/integration/impl/GetElementsIT.java
- store-implementation/map-store/src/main/java/uk/gov/gchq/gaffer/mapstore/impl/AddElementsHandler.java
- store-implementation/map-store/src/main/java/uk/gov/gchq/gaffer/mapstore/impl/GetElementsUtil.java
- store-implementation/map-store/src/main/java/uk/gov/gchq/gaffer/mapstore/impl/MapImpl.java
- store-implementation/parquet-store/src/main/java/uk/gov/gchq/gaffer/parquetstore/query/QueryGenerator.java
This should let the input to the `MapStore`'s `GetElements` be an `Element`, as well as well as an `ElementSeed`.
Marked as draft as some test for this might be a good idea.
- Resolve #2421
> gh-2421: Change MapStore GetElements to handle Elements

- .github/workflows/release-standalone.yaml
This reverts commit aec4d49b5f96ac66b9abe9d5546d641addd7a3a8.
> gh-2544: Revert "gh-2543: Change release standalone jdk to v1 (#2545)"

- README.md
- core/graph/README.md
- core/operation/README.md
- core/store/src/main/java/uk/gov/gchq/gaffer/store/schema/SchemaOptimiser.java
- example/road-traffic/README.md
- rest-api/README.md
- rest-api/common-rest/src/main/java/uk/gov/gchq/gaffer/rest/SystemProperty.java
- store-implementation/accumulo-store/README.md
- store-implementation/accumulo-store/sample-files/store.properties.sample
- store-implementation/federated-store/README.md
- store-implementation/hbase-store/README.md
- store-implementation/parquet-store/README.md
> gh-2565: Update links to Gaffer docs in all files

- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedStore.java
Removing redundant adding of GetTraitHandler from addAdditionalOperationHandlers() because it has its own method getGetTraitsHandler().
> gh-2560-getTraitsOperation

- store-implementation/hbase-store/README.md
- store-implementation/hbase-store/src/main/java/uk/gov/gchq/gaffer/hbasestore/HBaseStore.java
> gh-2556: Add HBaseStore deprecated tag, javadocs and note to README

- example/basic/basic-model/pom.xml
- example/federated-demo/pom.xml
- example/road-traffic/road-traffic-generators/pom.xml
- example/road-traffic/road-traffic-model/pom.xml
- example/road-traffic/road-traffic-rest/pom.xml
- integration-test/pom.xml
- library/flink-library/pom.xml
- library/hdfs-library/pom.xml
- library/spark/spark-accumulo-library/pom.xml
- library/spark/spark-library/pom.xml
- pom.xml
- rest-api/accumulo-rest/pom.xml
- rest-api/hbase-rest/pom.xml
- store-implementation/accumulo-store/pom.xml
- store-implementation/federated-store/pom.xml
- store-implementation/hbase-store/pom.xml
Log4j has been replaced with Reload4j. Maven enforcer plugin is also introduced to prevent future classpath problems if new or upgraded dependencies try to pull in Log4j or other related conflicting dependencies.
- Resolve #2602
> Gh-2602: Replace Log4j with Reload4j

- store-implementation/accumulo-store/src/main/java/uk/gov/gchq/gaffer/accumulostore/operation/handler/GetElementsWithinSetHandler.java
- store-implementation/accumulo-store/src/main/java/uk/gov/gchq/gaffer/accumulostore/retriever/AccumuloSetRetriever.java
- store-implementation/accumulo-store/src/test/java/uk/gov/gchq/gaffer/accumulostore/operation/handler/GetElementsWithinSetHandlerTest.java
- store-implementation/accumulo-store/src/test/java/uk/gov/gchq/gaffer/accumulostore/retriever/impl/AccumuloIDWithinSetRetrieverTest.java
GetElementsWithinSet was not filtering view properties. The bug has been identified and fixed. Further tests have been added to check that the fix is functioning correctly.
- Resolve #2562
> Gh 2562 GetElementsWithinSet not allowing for the exclusion of properties - Gaffer v1

- example/road-traffic/road-traffic-generators/src/main/java/uk/gov/gchq/gaffer/traffic/generator/RoadTrafficDataLoader.java
- example/road-traffic/road-traffic-rest/src/main/java/uk/gov/gchq/gaffer/traffic/listeners/ConsoleBanner.java
- example/road-traffic/road-traffic-rest/src/main/java/uk/gov/gchq/gaffer/traffic/listeners/DataLoader.java
- example/road-traffic/road-traffic-rest/src/test/java/uk.gov.gchq.gaffer.traffic/RoadTrafficTestQueries.java
Hi. I have replaced instances of java.util.logging.Logger to SLF4J. I have also cleaned up inconsistent use of logging strings in the files that were using java.uitl.logging.Logger. Let me know if any further changes are required. Many thanks.
> gh-2662: Investigate replacing java.util.logging.Logger with SLF4J

- rest-api/core-rest/src/main/java/uk/gov/gchq/gaffer/rest/service/v2/GraphConfigurationServiceV2.java
- rest-api/core-rest/src/main/java/uk/gov/gchq/gaffer/rest/service/v2/IGraphConfigurationServiceV2.java
- rest-api/core-rest/src/test/java/uk/gov/gchq/gaffer/rest/service/v2/GraphConfigurationServiceV2Test.java
- rest-api/spring-rest/src/main/java/uk/gov/gchq/gaffer/rest/controller/GraphConfigurationController.java
- rest-api/spring-rest/src/main/java/uk/gov/gchq/gaffer/rest/controller/IGraphConfigurationController.java
- rest-api/spring-rest/src/test/java/uk/gov/gchq/gaffer/rest/controller/GraphConfigurationControllerTest.java
> gh-2669: Added new aggregation function endpoints

- core/serialisation/src/test/java/uk/gov/gchq/gaffer/serialisation/implementation/MultiSerialiserTest.java
> Gh-2591: Tests involving Strings fail when run on Windows 

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
> Gh-2776: Create issue templates

- core/type/src/main/java/uk/gov/gchq/gaffer/types/FreqMap.java
- core/type/src/main/java/uk/gov/gchq/gaffer/types/TypeSubTypeValue.java
- core/type/src/main/java/uk/gov/gchq/gaffer/types/TypeValue.java
- library/sketches-library/src/main/java/uk/gov/gchq/gaffer/sketches/clearspring/cardinality/serialisation/json/HyperLogLogPlusJsonDeserialiser.java
- library/sketches-library/src/main/java/uk/gov/gchq/gaffer/sketches/clearspring/cardinality/serialisation/json/HyperLogLogPlusWithOffers.java
- library/sketches-library/src/test/java/uk/gov/gchq/gaffer/sketches/clearspring/cardinality/serialisation/json/HyperLogLogPlusJsonDeserialiserTest.java
- library/sketches-library/src/test/java/uk/gov/gchq/gaffer/sketches/clearspring/cardinality/serialisation/json/HyperLogLogPlusJsonSerialisationTest.java
`HyperLogLogPlus` was attempting to add the text version of the `JsonNode` which returned an empty string for an object. Have now reworked so the `JsonNode` is now examined and if a `class` field is found attempts to instantiate the object and send this to the `HyperLogLogPlus`.
- Resolve #2749
> Gh-2749: Hllp is not aggregated properly with TSV

- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedStore.java
- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/operation/FederatedOperation.java
`userRequestingDefaultGraphsOverride` removed as `graphIds` can be used instead.
- Resolve #2766
> Gh-2766: Removed userRequestingDefaultGraphsOverride

- core/operation/src/main/java/uk/gov/gchq/gaffer/named/operation/NamedOperation.java
Resolves issue: #2845 
Updated class variable `parameter` to be of type `Map`.
> Gh-2845: Update class variable to use Map interface

- core/operation/src/main/java/uk/gov/gchq/gaffer/named/operation/NamedOperation.java
Co-authored-by: t92549 <80890692+t92549@users.noreply.github.com>
- Resolve #2857
> Cherry-pick gh-2845: update class var parameter to use Map interface (#2846)

- library/spark/spark-library/pom.xml
- pom.xml
- rest-api/core-rest/pom.xml
- rest-api/spring-rest/pom.xml
- store-implementation/proxy-store/pom.xml
> Gh-2868: ProxyStore Jersey dependency issues

- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreCache.java
- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreCacheTransient.java
- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/operation/handler/impl/FederatedRemoveGraphHandlerTest.java
> gh-2880 RemoveGraph errors when graphId does not exist

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- README.md
- core/data/src/main/java/uk/gov/gchq/gaffer/data/generator/CsvGenerator.java
- core/data/src/main/java/uk/gov/gchq/gaffer/data/generator/Neo4jCsvGenerator.java
- core/data/src/main/java/uk/gov/gchq/gaffer/data/generator/NeptuneCsvGenerator.java
- core/operation/src/main/java/uk/gov/gchq/gaffer/operation/impl/output/ToCsv.java
- core/operation/src/test/java/uk/gov/gchq/gaffer/operation/impl/output/ToCsvTest.java
- core/store/src/main/java/uk/gov/gchq/gaffer/store/operation/handler/output/ToCsvHandler.java
> Gh 2940: Merge develop into v2-alpha

- example/road-traffic/road-traffic-rest/pom.xml
- pom.xml
The versions of JUnit and JUnit Suites need to be kept in sync when upgrading their versions.
- Resolve #2948
> Gh-2948: Upgrade JUnit and related dependencies and plugins

- store-implementation/accumulo-store/src/test/java/uk/gov/gchq/gaffer/accumulostore/MiniAccumuloStore.java
This commit refactors the code to address the scenario where the zookeepers property is null. The modified code now checks if the zookeepers property is null, and if so, it sets the ZooKeeperPort to the default value. This change ensures that a NullPointerException is avoided when accessing the zookeepers property and provides a more robust behavior in the case of a missing or null value.
> Gh-2997: Prevented a NullPointerException being thrown.

- core/store/src/main/java/uk/gov/gchq/gaffer/store/Store.java
- core/store/src/test/java/uk/gov/gchq/gaffer/store/StoreTest.java
Previously, the CancelScheduledJobHandler would throw an OperationException with the message 'JobTracker not enabled' if used when Jobs were not enabled. This issue arose because the handler was being added even when Jobs were not enabled. To resolve this, changes were made to ensure that the CancelScheduledJobHandler is only added when Jobs are enabled. This ensures that the handler functions correctly and prevents the unnecessary exception from being thrown.
> Gh-2944: Ensure CancelScheduledJobHandler is added only when Jobs are enabled.

- library/spark/pom.xml
> Gh-2680: Fix repo priority in spark-library

- rest-api/common-rest/pom.xml
- rest-api/common-rest/src/main/resources/version.properties
- rest-api/core-rest/pom.xml
- rest-api/core-rest/src/main/java/uk/gov/gchq/gaffer/rest/application/ApplicationConfigV2.java
- rest-api/core-rest/src/main/java/uk/gov/gchq/gaffer/rest/service/v2/VersionServiceV2.java
- rest-api/core-rest/src/test/java/uk/gov/gchq/gaffer/rest/service/v2/VersionServiceV2Test.java
- rest-api/core-rest/src/test/resources/version.properties
- rest-api/spring-rest/pom.xml
- rest-api/spring-rest/src/main/java/uk/gov/gchq/gaffer/rest/controller/VersionController.java
- rest-api/spring-rest/src/test/java/uk/gov/gchq/gaffer/rest/controller/VersionControllerTest.java
- rest-api/spring-rest/src/test/resources/version.properties
Adds a simple endpoint to both the spring and core (jersey) API that returns the Gaffer version string contained in the `common-rest` library. The version is automatically kept in line with the maven version used for the project by simply expanding that variable into a properties file at build time that is embedded in the JAR and read back at runtime.
Unit tests provided for both that mock a request to the endpoint and validate the response, but also performed a sanity manual test to ensure the endpoint appears in the swagger UI and has relevant information/parameters.
- Resolve #2837
> Gh-2837: Endpoint for getting the Gaffer version

- rest-api/core-rest/src/main/java/uk/gov/gchq/gaffer/rest/service/v2/GraphConfigurationServiceV2.java
- rest-api/core-rest/src/main/java/uk/gov/gchq/gaffer/rest/service/v2/IGraphConfigurationServiceV2.java
- rest-api/core-rest/src/test/java/uk/gov/gchq/gaffer/rest/service/v2/GraphConfigurationServiceV2Test.java
- rest-api/spring-rest/src/main/java/uk/gov/gchq/gaffer/rest/controller/GraphConfigurationController.java
- rest-api/spring-rest/src/main/java/uk/gov/gchq/gaffer/rest/controller/IGraphConfigurationController.java
- rest-api/spring-rest/src/test/java/uk/gov/gchq/gaffer/rest/controller/GraphConfigurationControllerTest.java
Adds a simple endpoint to spring-rest and core-rest which returns the store that is used in your Gaffer graph. 
- Resolve #2838
> Gh-2838: Create endpoint to get store type

- library/tinkerpop/src/test/java/uk/gov/gchq/gaffer/tinkerpop/generator/GafferEdgeGeneratorTest.java
- library/tinkerpop/src/test/java/uk/gov/gchq/gaffer/tinkerpop/generator/GafferEntityGeneratorTest.java
- library/tinkerpop/src/test/java/uk/gov/gchq/gaffer/tinkerpop/generator/GafferPopEdgeGeneratorTest.java
- library/tinkerpop/src/test/java/uk/gov/gchq/gaffer/tinkerpop/generator/GafferPopElementGeneratorTest.java
- library/tinkerpop/src/test/java/uk/gov/gchq/gaffer/tinkerpop/generator/GafferPopVertexGeneratorTest.java
Added testing to GafferPopElementGenerator to increase test coverage. Also updated testing from JUnit to AssertJ for the other generator classes to aid with improving assertion readability (#3014). Improved test coverage of GafferPopVertexGenerator and GafferPopEdgeGenerator classes.
- Resolve #3056
> Gh-3056: Add testing to GafferPopElementGenerator

- store-implementation/accumulo-store/src/main/java/uk/gov/gchq/gaffer/accumulostore/key/core/AbstractCoreKeyAccumuloElementConverter.java
- store-implementation/accumulo-store/src/main/java/uk/gov/gchq/gaffer/accumulostore/utils/AccumuloStoreConstants.java
- store-implementation/accumulo-store/src/test/java/uk/gov/gchq/gaffer/accumulostore/integration/FirstLastIT.java
Following some investigation the bug appears to be due to the Accumulo timestamp.
Looking at the Accumulo docs it is stated that if you insert a key with same rowID, column and timestamp then the behaviour is non-deterministic, this is what was happening when aggregating as the timestamp is being hardcoded to a default value and rowID and column would be the same ([see](https://accumulo.apache.org/1.8/accumulo_user_manual.html#_versioning_iterators_and_timestamps))
The solution here will apply a timestamp to elements that are aggregated via time sensitive aggregation functions such as, First and Last. This should fix the original issue and ensure no unnecessary timestamps are added to data that doesn't need them.
Integration test has been added to ensure this is fixed.
- Resolve #2891
> Gh-2891: Aggregate First and Last properties consistently in Accumulo

- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/operation/handler/impl/FederatedOperationHandler.java
Adds in logic to skip the default merge function if only one graph or if no common groups between graph schemas, instead it will just flatten the current list of results and return.
Unsure if there are existing tests for this functionality or the integration tests need fixing first under #3058 
- Resolve #3053
> Gh-3053: ApplyViewToElementsFunction optimisations

- core/common-util/src/test/java/uk/gov/gchq/gaffer/commonutil/TestPropertyNames.java
- library/tinkerpop/src/test/java/uk/gov/gchq/gaffer/tinkerpop/GafferPopVertexTest.java
Improves the test coverage and quality of the testing (measured from mutation testing) on the `GafferPopVertex` class.
Now above 80% coverage and moved to assertJ where possible.
- Resolve #3083
> Gh-3083: Improve testing of gafferpopvertex

- library/tinkerpop/src/main/java/uk/gov/gchq/gaffer/tinkerpop/generator/GafferEntityGenerator.java
- library/tinkerpop/src/test/java/uk/gov/gchq/gaffer/tinkerpop/generator/GafferEntityGeneratorTest.java
Improves tests for the `GafferEntityGenerator` coverage now > 80%
Small tweak to the main class so it checks for null values and to use easier to read lambdas.
- Resolve #3098
> Gh-3098: Improve Testing of GafferEntityGenerator

- library/tinkerpop/src/test/java/uk/gov/gchq/gaffer/tinkerpop/GafferPopEdgeTest.java
Expands unit tests for the GafferPopEdges to more rigorously test the GafferPopProperty class is being used and created correctly when properties are added to an edge. Now has  > 80% coverage. 
- Resolve #3100
> Gh-3100: Add unit testing to GafferPopProperty

- .github/workflows/codeql.yaml
- .github/workflows/continuous-integration-legacy.yaml
- .github/workflows/continuous-integration.yaml
- .github/workflows/create-hotfix-branch.yaml
- .github/workflows/create-release-branch.yaml
- .github/workflows/link-issue.yml
- .github/workflows/release-standalone.yaml
- .github/workflows/release.yaml
- .github/workflows/update-koryphe-version.yaml
> Gh-3103: Remove gafferpy update trigger

- library/tinkerpop/src/main/java/uk/gov/gchq/gaffer/tinkerpop/service/GafferPopNamedOperationService.java
- library/tinkerpop/src/test/java/uk/gov/gchq/gaffer/tinkerpop/service/GafferPopNamedOperationServiceFactoryTest.java
- library/tinkerpop/src/test/java/uk/gov/gchq/gaffer/tinkerpop/service/GafferPopNamedOperationServiceIT.java
- library/tinkerpop/src/test/java/uk/gov/gchq/gaffer/tinkerpop/service/GafferPopNamedOperationServiceTest.java
- library/tinkerpop/src/test/resources/gaffer/map-store.properties
Includes a fix for missing Generics in the class itself
- Resolve #3091
> Gh-3091: Improve testing of GafferPop NamedOperationService

- library/tinkerpop/src/main/java/uk/gov/gchq/gaffer/tinkerpop/GafferPopVertexProperty.java
- library/tinkerpop/src/test/java/uk/gov/gchq/gaffer/tinkerpop/GafferPopVertexTest.java
Improves the testing on `GafferPopVertexProperty` class to above > 80% coverage.
Slight tweak to reduce mock duplication in the existing test class too.
- Resolve #3108
> Gh-3108: Improve testing for GafferPopVertexProperty

- library/tinkerpop/src/main/java/uk/gov/gchq/gaffer/tinkerpop/service/GafferPopNamedOperationService.java
- library/tinkerpop/src/test/java/uk/gov/gchq/gaffer/tinkerpop/service/GafferPopNamedOperationServiceIT.java
- library/tinkerpop/src/test/java/uk/gov/gchq/gaffer/tinkerpop/service/GafferPopNamedOperationServiceTest.java
Some Generics handing is not ideal. This is due to the implementation of generators, how this class is used and TinkerPop itself (rawtype `Map`).
- Resolve #3106
> Gh-3106: Refactor GafferPopNamedOperationService

- .github/workflows/codeql.yaml
- .github/workflows/continuous-integration-legacy.yaml
- .github/workflows/continuous-integration.yaml
- .github/workflows/release-standalone.yaml
- .github/workflows/release.yaml
- .github/workflows/update-koryphe-version.yaml
Includes moving the copyright check to a dedicated job to prevent it interrupting tests.
- Resolve #3150
> Gh-3150: Upgrade Actions versions

- library/sketches-library/pom.xml
> Gh-3159: Datasketches library missing from sketches deploy JAR

- library/tinkerpop/src/main/java/uk/gov/gchq/gaffer/tinkerpop/GafferPopGraph.java
Fixes issue with the current Gafferpop library where the resulting operation chain that would be ran on the graph included the element generators specific to Gafferpop. They are now called locally on the results of a chain or before running a chain so that the target graph does not need to be aware of the Gafferpop library. This also avoids any serialisation errors when using the proxy store to enable gremlin on an existing graph.
*Other fixes*
- Fixed issue with using Edge IDs as seeds
- Stopped the `View` being added twice to `GetAdjacentIds` call as this was removing all returned vertexes.
Tested some of this manually spinning up a Map Store REST and attaching a gremlin server via a proxy store to allow querying.
- Resolve #3183
> Gh-3183 Remove gafferpop specifics from operation chains

- library/tinkerpop/src/main/java/uk/gov/gchq/gaffer/tinkerpop/GafferPopGraph.java
Costly logging should only display now if the SLF4J log level is enabled. 
- Resolve #2994
> Gh-2994: Make gremlin logging configurable

- .github/workflows/release.yaml
This prevents the situation where mv cannot move if directory not empty
- Resolve #3178
> Gh-3178: Javadoc release file copy problem

- core/common-util/pom.xml
- core/common-util/src/main/java/uk/gov/gchq/gaffer/commonutil/otel/OtelUtil.java
- core/graph/src/main/java/uk/gov/gchq/gaffer/graph/Graph.java
- core/graph/src/main/java/uk/gov/gchq/gaffer/graph/GraphConfig.java
- core/graph/src/test/java/uk/gov/gchq/gaffer/graph/GraphConfigTest.java
- core/graph/src/test/java/uk/gov/gchq/gaffer/graph/GraphTest.java
- core/graph/src/test/resources/graphConfig.json
- core/store/src/main/java/uk/gov/gchq/gaffer/store/Store.java
- core/store/src/main/java/uk/gov/gchq/gaffer/store/operation/handler/OperationChainHandler.java
- pom.xml
Adds a basic implementation of Open Telemetry that will record Spans across executions of Operations/OperationChains. Can be toggled on via a `otelActive` option in the `graphConfig.json` (off by default).  Hopefully is a useful start point to be expanded on if required.
Is difficult one to demonstrate via unit testing but been manually tested to ensure Spans look useful with relevant data via a `Jaeger` UI. Uses the auto configure feature of Open Telemetry so can be easily configured where and how to export data to via environment variables e.g.
- `OTEL_SERVICE_NAME=gaffer-rest` - sets the service name to `gaffer-rest`
- `OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://jaeger:4317` - sets the endpoint to export traces to e.g. `Jaeger`
- `OTEL_TRACES_EXPORTER=console` - sets the exporter to …
> Gh-3187: Add Open Telemetry proof of concept

- example/basic/basic-rest/pom.xml
- example/federated-demo/pom.xml
- example/road-traffic/road-traffic-rest/pom.xml
- pom.xml
- rest-api/accumulo-rest/pom.xml
- rest-api/map-rest/pom.xml
Fixes both causes of the error message described in the issue.
- Resolve #3198
> Gh-3198: Fix m2e dependency-plugin unpack error

- library/tinkerpop/src/main/java/uk/gov/gchq/gaffer/tinkerpop/GafferPopGraph.java
- library/tinkerpop/src/main/java/uk/gov/gchq/gaffer/tinkerpop/GafferPopGraphVariables.java
- library/tinkerpop/src/main/java/uk/gov/gchq/gaffer/tinkerpop/process/traversal/step/GafferPopGraphStep.java
- library/tinkerpop/src/main/java/uk/gov/gchq/gaffer/tinkerpop/process/traversal/strategy/optimisation/GafferPopGraphStepStrategy.java
- library/tinkerpop/src/test/java/uk/gov/gchq/gaffer/tinkerpop/GafferPopFederatedIT.java
- library/tinkerpop/src/test/java/uk/gov/gchq/gaffer/tinkerpop/GafferPopGraphIT.java
- library/tinkerpop/src/test/java/uk/gov/gchq/gaffer/tinkerpop/GafferPopGraphVariablesTest.java
- library/tinkerpop/src/test/java/uk/gov/gchq/gaffer/tinkerpop/process/traversal/stategy/GafferPopGraphStepStrategyTest.java
- library/tinkerpop/src/test/java/uk/gov/gchq/gaffer/tinkerpop/util/GafferPopFederatedTestUtil.java
Adds the ability to override a limited set of graph variables when doing a gremlin query. This utilises the `with()` feature of gremlin that will attach a `OptionsStrategy` to the query that can then be parsed for the relevant options passed in. 
To implement this it required creating a custom traversal mechanism for gremlin `GraphStep`s so that we can override and parse the options on the query. Adding this step also allowed for a small optimisation to ensure any `hasLabel` type queries on the original `GraphStep` are parsed to create a representative Gaffer `View`. The intention is that additional custom traversal steps are added in future to optimise the mapping of gremlin to standard Gaffer operations.
As an example this allows the following:
```java
g.with("userId", "user").V()   // …
```
> Gh-2996: Ability to pass config in gremlin queries

- library/tinkerpop/src/main/java/uk/gov/gchq/gaffer/tinkerpop/GafferPopGraph.java
- library/tinkerpop/src/main/java/uk/gov/gchq/gaffer/tinkerpop/GafferPopGraphVariables.java
- library/tinkerpop/src/test/java/uk/gov/gchq/gaffer/tinkerpop/GafferPopGraphIT.java
- library/tinkerpop/src/test/java/uk/gov/gchq/gaffer/tinkerpop/util/GafferPopTestUtil.java
- library/tinkerpop/src/test/resources/gafferpop-test.properties
> Gh-2989: Add configurable GetAllElements Limit to Tinkerpop

- library/tinkerpop/src/main/java/uk/gov/gchq/gaffer/tinkerpop/GafferPopGraph.java
- library/tinkerpop/src/test/java/uk/gov/gchq/gaffer/tinkerpop/GafferPopFederatedIT.java
Added a few more tests of a federated store with a GafferPopGraph. These test whether the .with() config options allow users to specify the graph they wish to target for results using Gremlin. 
Also an additional fix in GafferPopGraph which prevented Gremlin queries seeding with edge IDs in cases where edges were not directed. 
Note: docs will need to be added that explain to users how to use the .with() to query federated graphs. 
- Resolve #3200
> Gh-3200: Additional Federated Stores Tinkerpop tests

- library/tinkerpop/src/main/java/uk/gov/gchq/gaffer/tinkerpop/GafferPopVertex.java
- library/tinkerpop/src/main/java/uk/gov/gchq/gaffer/tinkerpop/GafferPopVertexProperty.java
- library/tinkerpop/src/test/java/uk/gov/gchq/gaffer/tinkerpop/GafferPopVertexTest.java
Set a proper ID for GafferPopVertexProperties so that equals and hashCode work as expected
simplify GafferPopVertex.properties() method
add unit test to catch error
- Resolve #3210
> Gh-3210: Fix GafferPopVertex.properties() output

- library/time-library/src/main/java/uk/gov/gchq/gaffer/time/BoundedTimestampSet.java
- pom.xml
Also enables the cache and bumps plugin version to latest
- Resolve #3157
> Gh-3157: Fix PMD plugin unnecessary warning

- core/operation/src/main/java/uk/gov/gchq/gaffer/operation/OperationChain.java
- core/operation/src/test/java/uk/gov/gchq/gaffer/operation/impl/ValidateOperationChainTest.java
- library/tinkerpop/src/main/java/uk/gov/gchq/gaffer/tinkerpop/GafferPopGraph.java
- library/tinkerpop/src/main/java/uk/gov/gchq/gaffer/tinkerpop/process/traversal/step/GafferPopGraphStep.java
- store-implementation/proxy-store/src/main/java/uk/gov/gchq/gaffer/proxystore/response/deserialiser/impl/DefaultResponseDeserialiser.java
Fixes most of the issues in the original issue, two minor fixes:
1. ensures the correct method is called in the `GafferPopGraphStep` 
2. Prevents `null` operation chain options.
Added work around to main serialisation error in the proxy store so that it attempts to deserialise element iterators. This will be fixed in a larger rework of the proxy store so that it does not need to double deserialise.
- Resolve #3209
> Gh-3209: GetAll Limit fails on Proxy Store

- library/tinkerpop/src/main/java/uk/gov/gchq/gaffer/tinkerpop/GafferPopEdge.java
- library/tinkerpop/src/test/java/uk/gov/gchq/gaffer/tinkerpop/GafferPopEdgeTest.java
- library/tinkerpop/src/test/java/uk/gov/gchq/gaffer/tinkerpop/GafferPopFederatedIT.java
- library/tinkerpop/src/test/java/uk/gov/gchq/gaffer/tinkerpop/GafferPopVertexTest.java
- library/tinkerpop/src/test/java/uk/gov/gchq/gaffer/tinkerpop/generator/GafferEdgeGeneratorTest.java
- library/tinkerpop/src/test/java/uk/gov/gchq/gaffer/tinkerpop/generator/GafferPopEdgeGeneratorTest.java
Implemented a fix which will use an Operation Chain to search the graph for the vertex by ID to get the right results. Fixes 32 cucumber tests. 
- Resolve #3219
> Gh-3219: Fix inV() and outV() missing results

- .github/workflows/continuous-integration.yaml
- README.md
- core/cache/README.md
- core/data/README.md
- core/graph/README.md
- core/operation/README.md
- core/serialisation/README.md
- core/store/README.md
- example/road-traffic/README.md
- integration-test/README.md
- library/bitmap-library/README.md
- library/flink-library/README.md
- library/sketches-library/README.md
- library/spark/README.md
- library/time-library/README.md
- library/tinkerpop/README.md
- rest-api/core-rest/README.md
- rest-api/spring-rest/README.md
- store-implementation/accumulo-store/README.md
- store-implementation/federated-store/README.md
- store-implementation/map-store/README.md
- store-implementation/proxy-store/README.md
Also adds CI check to avoid future broken links
- Resolve #3232
> Gh-3232: Fix broken links in READMEs

- library/tinkerpop/src/main/java/uk/gov/gchq/gaffer/tinkerpop/GafferPopGraph.java
- library/tinkerpop/src/test/java/uk/gov/gchq/gaffer/tinkerpop/GafferPopGraphIT.java
- library/tinkerpop/src/test/resources/gaffer/tstv-schema/elements.json
- library/tinkerpop/src/test/resources/gaffer/tstv-schema/types.json
Adds basic support for seeding queries in GafferPop with TypeSubTypeValues by parsing specific string formats separated via a `|` to construct the correct object to seed the query with. 
As an example `g.V("t:type|st:sub|v:value")` -> `new TypeSubTypeValue("type", "sub", "value")`
- Resolve #3234
> Gh-3234: TypeSubTypeValue Seeded Query Support in GafferPop

- library/tinkerpop/src/main/java/uk/gov/gchq/gaffer/tinkerpop/GafferPopEdge.java
- library/tinkerpop/src/main/java/uk/gov/gchq/gaffer/tinkerpop/GafferPopGraph.java
- library/tinkerpop/src/test/java/uk/gov/gchq/gaffer/tinkerpop/GafferPopFederatedIT.java
- library/tinkerpop/src/test/java/uk/gov/gchq/gaffer/tinkerpop/GafferPopGraphIT.java
- library/tinkerpop/src/test/java/uk/gov/gchq/gaffer/tinkerpop/process/traversal/step/GafferPopHasStepIT.java
- library/tinkerpop/src/test/java/uk/gov/gchq/gaffer/tinkerpop/util/GafferPopModernTestUtils.java
Able to now query edges with the id in format [1, knows, 2] in addition to [1, 2]. If the label is included this is used in the GetElements View.
Label also added to the returned edge id.
- Resolve #3223
> Gh-3223: Change GafferPopEdge id representation

- rest-api/spring-rest/src/main/java/uk/gov/gchq/gaffer/rest/GafferWebApplication.java
Fixes a small bug with the swagger UI not picking up the correct URL and using http in some cases.
- Resolve #3241
> Gh-3241: Swagger UI not always using correct server URL

- rest-api/spring-rest/src/main/java/uk/gov/gchq/gaffer/rest/config/GremlinConfig.java
I thought this was saying it wasn't finding the config at the default location
> Make gremlin config message clearer

- rest-api/spring-rest/src/main/java/uk/gov/gchq/gaffer/rest/GafferWebApplication.java
> Gh-3272 Make Swagger Server URL dynamic

- core/store/src/main/java/uk/gov/gchq/gaffer/store/library/GraphLibrary.java
- store-implementation/simple-federated-store/src/main/java/uk/gov/gchq/gaffer/federated/simple/FederatedStore.java
- store-implementation/simple-federated-store/src/main/java/uk/gov/gchq/gaffer/federated/simple/operation/AddGraph.java
- store-implementation/simple-federated-store/src/main/java/uk/gov/gchq/gaffer/federated/simple/operation/handler/FederatedOperationHandler.java
- store-implementation/simple-federated-store/src/main/java/uk/gov/gchq/gaffer/federated/simple/operation/handler/add/AddGraphHandler.java
- store-implementation/simple-federated-store/src/main/java/uk/gov/gchq/gaffer/federated/simple/operation/handler/get/GetSchemaHandler.java
- store-implementation/simple-federated-store/src/test/java/uk/gov/gchq/gaffer/federated/simple/FederatedStoreIT.java
- store-implementation/simple-federated-store/src/test/java/uk/gov/gchq/gaffer/federated/simple/FederatedStoreTest.java
- store-implementation/simple-federated-store/src/test/java/uk/gov/gchq/gaffer/federated/simple/operation/AddGraphTest.java
Adds an `AddGraph` operation to the simple federated POC. To do this some additional logic in the operation handlers has also been added as well as, ensuring a prefix is added to any sub graphs in the federated store to avoid collisions with other instances. 
- Resolve #3279
> Gh-3279: AddGraph Operation for Federated POC

- rest-api/spring-rest/src/main/java/uk/gov/gchq/gaffer/rest/controller/OperationController.java
> Gh-3281: add examples for /operations/execute

- store-implementation/simple-federated-store/src/main/java/uk/gov/gchq/gaffer/federated/simple/FederatedStore.java
- store-implementation/simple-federated-store/src/main/java/uk/gov/gchq/gaffer/federated/simple/merge/DefaultResultAccumulator.java
- store-implementation/simple-federated-store/src/main/java/uk/gov/gchq/gaffer/federated/simple/operation/handler/FederatedOperationHandler.java
- store-implementation/simple-federated-store/src/main/java/uk/gov/gchq/gaffer/federated/simple/operation/handler/get/GetAllGraphIdsHandler.java
- store-implementation/simple-federated-store/src/test/java/uk/gov/gchq/gaffer/federated/simple/FederatedStoreIT.java
- store-implementation/simple-federated-store/src/test/java/uk/gov/gchq/gaffer/federated/simple/FederatedStoreTest.java
- store-implementation/simple-federated-store/src/test/java/uk/gov/gchq/gaffer/federated/simple/operation/AddGraphTest.java
- store-implementation/simple-federated-store/src/test/java/uk/gov/gchq/gaffer/federated/simple/operation/RemoveGraphTest.java
Fairly simple just moves to using the default gaffer cache for storing graphs that have been added to the federated store.
- Resolve #3288
> Gh 3288: Store Graphs in cache in federated POC

- store-implementation/simple-federated-store/src/main/java/uk/gov/gchq/gaffer/federated/simple/FederatedStore.java
- store-implementation/simple-federated-store/src/main/java/uk/gov/gchq/gaffer/federated/simple/FederatedStoreProperties.java
- store-implementation/simple-federated-store/src/main/java/uk/gov/gchq/gaffer/federated/simple/merge/DefaultResultAccumulator.java
- store-implementation/simple-federated-store/src/main/java/uk/gov/gchq/gaffer/federated/simple/merge/FederatedResultAccumulator.java
- store-implementation/simple-federated-store/src/main/java/uk/gov/gchq/gaffer/federated/simple/operation/handler/FederatedOutputHandler.java
- store-implementation/simple-federated-store/src/test/java/uk/gov/gchq/gaffer/federated/simple/FederatedStoreTest.java
- store-implementation/simple-federated-store/src/test/java/uk/gov/gchq/gaffer/federated/simple/merge/DefaultResultAccumulatorTest.java
Added ability to configure aspects of the simple federated store using store properties. 
- Resolve #3290
> Gh-3290: Configure with properties in federated POC

- store-implementation/simple-federated-store/src/main/java/uk/gov/gchq/gaffer/federated/simple/FederatedStore.java
- store-implementation/simple-federated-store/src/main/java/uk/gov/gchq/gaffer/federated/simple/operation/GetAllGraphInfo.java
- store-implementation/simple-federated-store/src/main/java/uk/gov/gchq/gaffer/federated/simple/operation/handler/get/GetAllGraphInfoHandler.java
- store-implementation/simple-federated-store/src/test/java/uk/gov/gchq/gaffer/federated/simple/FederatedStoreIT.java
- store-implementation/simple-federated-store/src/test/java/uk/gov/gchq/gaffer/federated/simple/util/ModernDatasetUtils.java
Added a GetAllGraphInfo operation to the POC simple federated store. This can easily be modified to have additional fields within the map, including auths. Operation returns key information about the configuration of the store.
- Resolve #3291
> Gh-3291: Add GetAllGraphInfo operation to POC federated store

- store-implementation/simple-federated-store/src/main/java/uk/gov/gchq/gaffer/federated/simple/FederatedStore.java
- store-implementation/simple-federated-store/src/main/java/uk/gov/gchq/gaffer/federated/simple/merge/operator/ElementAggregateOperator.java
- store-implementation/simple-federated-store/src/main/java/uk/gov/gchq/gaffer/federated/simple/operation/handler/FederatedOperationHandler.java
- store-implementation/simple-federated-store/src/test/java/uk/gov/gchq/gaffer/federated/simple/FederatedStoreIT.java
- store-implementation/simple-federated-store/src/test/java/uk/gov/gchq/gaffer/federated/simple/FederatedStoreTest.java
- store-implementation/simple-federated-store/src/test/resources/modern/schema/schema.json
There was an issue where the iterators from Accumulo could be exhausted or closed before the merging of elements had completed. There's not a great way around this other than to buffer the data into a set before using for merging. This does of course increase memory usage but might be faster overall.
(Also the previous solution was still technically buffering to memory with a `distict()` call).
- Resolve #3295
> Gh-3295: Fix issue with Accumulo iterators when smart merging Federated POC

- library/tinkerpop/src/test/java/uk/gov/gchq/gaffer/tinkerpop/util/modern/Person.java
- rest-api/spring-rest/src/main/java/uk/gov/gchq/gaffer/rest/config/GremlinConfig.java
- rest-api/spring-rest/src/main/java/uk/gov/gchq/gaffer/rest/config/GremlinWebSocketConfig.java
- rest-api/spring-rest/src/main/java/uk/gov/gchq/gaffer/rest/controller/GremlinController.java
- rest-api/spring-rest/src/main/java/uk/gov/gchq/gaffer/rest/handler/GremlinWebSocketHandler.java
- rest-api/spring-rest/src/test/java/uk/gov/gchq/gaffer/rest/controller/GremlinControllerTest.java
- rest-api/spring-rest/src/test/java/uk/gov/gchq/gaffer/rest/integration/handler/GremlinWebSocketIT.java
Adds configurable timeout to the REST API for gremlin queries, also enables running queries via endpoints as well as the normal websocket. Few bits of tidying as well.
- Resolve #3292
> Gh-3292: REST API Gremlin Timeout and Execute Endpoints

- store-implementation/simple-federated-store/pom.xml
- store-implementation/simple-federated-store/src/main/java/uk/gov/gchq/gaffer/federated/simple/FederatedStore.java
- store-implementation/simple-federated-store/src/main/java/uk/gov/gchq/gaffer/federated/simple/operation/ChangeGraphId.java
- store-implementation/simple-federated-store/src/main/java/uk/gov/gchq/gaffer/federated/simple/operation/handler/misc/ChangeGraphIdHandler.java
- store-implementation/simple-federated-store/src/test/java/uk/gov/gchq/gaffer/federated/simple/operation/ChangeGraphIdTest.java
- store-implementation/simple-federated-store/src/test/resources/accumulo-store.properties
PR adds a ChangeGraphId, mainly for accumulo stores, to the POC federated store. 
- Resolve #3299
> Gh-3299: Add ChangeGraphId operation to POC simple federated store

- core/store/src/main/java/uk/gov/gchq/gaffer/store/operation/handler/OperationChainHandler.java
- rest-api/spring-rest/src/main/java/uk/gov/gchq/gaffer/rest/controller/GremlinController.java
- rest-api/spring-rest/src/test/java/uk/gov/gchq/gaffer/rest/controller/GremlinControllerTest.java
Fixes the issue where the status was always reported as 200 on the Gremlin execute endpoints. They now fail with 500 and a message. 
Some misc fixes for open telemetry spans as well.
- Resolve #3303
> Gh-3303: No error reported when Gremlin endpoint fails

- library/tinkerpop/src/main/java/uk/gov/gchq/gaffer/tinkerpop/GafferPopGraph.java
Teeny fix - applies operation options at opChain and operation level for simple fed store and current fed store.
- Resolve #3305
> Gh-3305: Fix to apply OpOptions at OpChain level

- store-implementation/simple-federated-store/src/main/java/uk/gov/gchq/gaffer/federated/simple/FederatedStoreProperties.java
- store-implementation/simple-federated-store/src/main/java/uk/gov/gchq/gaffer/federated/simple/merge/DefaultResultAccumulator.java
- store-implementation/simple-federated-store/src/main/java/uk/gov/gchq/gaffer/federated/simple/merge/FederatedResultAccumulator.java
- store-implementation/simple-federated-store/src/main/java/uk/gov/gchq/gaffer/federated/simple/operation/handler/FederatedOperationHandler.java
- store-implementation/simple-federated-store/src/main/java/uk/gov/gchq/gaffer/federated/simple/operation/handler/FederatedOutputHandler.java
- store-implementation/simple-federated-store/src/test/java/uk/gov/gchq/gaffer/federated/simple/FederatedStoreIT.java
- store-implementation/simple-federated-store/src/test/java/uk/gov/gchq/gaffer/federated/simple/merge/DefaultResultAccumulatorTest.java
- store-implementation/simple-federated-store/src/test/java/uk/gov/gchq/gaffer/federated/simple/util/ModernDatasetUtils.java
Adds ability to set the merge classes via the operation options using the same property keys as you would through the store properties. 
This also added merge configuration for Map types along with, ability to add an exception list of graphs so a user can specify to run on all graphs except a defined list (this is the feature from #3224).
- Resolve #3308
> Gh-3308: Specify merge classes federated POC

- library/tinkerpop/src/test/resources/federatedStore/simple-fed-store.properties
- store-implementation/simple-federated-store/pom.xml
- store-implementation/simple-federated-store/src/main/java/uk/gov/gchq/gaffer/federated/simple/FederatedStore.java
- store-implementation/simple-federated-store/src/main/java/uk/gov/gchq/gaffer/federated/simple/FederatedStoreProperties.java
- store-implementation/simple-federated-store/src/main/java/uk/gov/gchq/gaffer/federated/simple/access/GraphAccess.java
- store-implementation/simple-federated-store/src/main/java/uk/gov/gchq/gaffer/federated/simple/operation/AddGraph.java
- store-implementation/simple-federated-store/src/main/java/uk/gov/gchq/gaffer/federated/simple/operation/handler/FederatedOperationHandler.java
- store-implementation/simple-federated-store/src/main/java/uk/gov/gchq/gaffer/federated/simple/operation/handler/FederatedOutputHandler.java
- store-implementation/simple-federated-store/src/main/java/uk/gov/gchq/gaffer/federated/simple/operation/handler/add/AddGraphHandler.java
- store-implementation/simple-federated-store/src/main/java/uk/gov/gchq/gaffer/federated/simple/operation/handler/get/GetAllGraphIdsHandler.java
- store-implementation/simple-federated-store/src/main/java/uk/gov/gchq/gaffer/federated/simple/operation/handler/get/GetAllGraphInfoHandler.java
- store-implementation/simple-federated-store/src/main/java/uk/gov/gchq/gaffer/federated/simple/operation/handler/get/GetSchemaHandler.java
- store-implementation/simple-federated-store/src/main/java/uk/gov/gchq/gaffer/federated/simple/operation/handler/misc/ChangeGraphIdHandler.java
- store-implementation/simple-federated-store/src/main/java/uk/gov/gchq/gaffer/federated/simple/operation/handler/misc/RemoveGraphHandler.java
- store-implementation/simple-federated-store/src/test/java/uk/gov/gchq/gaffer/federated/simple/FederatedStoreIT.java
- store-implementation/simple-federated-store/src/test/java/uk/gov/gchq/gaffer/federated/simple/FederatedStoreTest.java
- store-implementation/simple-federated-store/src/test/java/uk/gov/gchq/gaffer/federated/simple/access/GraphAccessTest.java
- store-implementation/simple-federated-store/src/test/java/uk/gov/gchq/gaffer/federated/simple/operation/AddGraphTest.java
- store-implementation/simple-federated-store/src/test/java/uk/gov/gchq/gaffer/federated/simple/operation/ChangeGraphIdTest.java
- store-implementation/simple-federated-store/src/test/java/uk/gov/gchq/gaffer/federated/simple/operation/RemoveGraphTest.java
- store-implementation/simple-federated-store/src/test/java/uk/gov/gchq/gaffer/federated/simple/util/FederatedTestUtils.java
Adds optional access controls for graphs added to federated stores to prevent users having visibility or modifying graphs they don't have access to.
Follows a similar concept to the old federated store by using the existing `AccessControlledResource` class and associated framework already in place. One main difference is `graphAuths` no longer exist they can instead be defined inside the `DefaultUserPredicate` or custom predicate, this would look something like the following if done via JSON:
```JSON
{
"readPredicate": {
"class": "uk.gov.gchq.gaffer.access.predicate.AccessPredicate",
"userPredicate": {
"class": "uk.gov.gchq.gaffer.access.predicate.user.DefaultUserPredicate",
"auths": [ "auth1", "auth2" ]
}
}
}
```
- Resolve #3300
> Gh-3300: Graph access controls for federated POC

- core/common-util/src/main/java/uk/gov/gchq/gaffer/commonutil/otel/OtelUtil.java
- core/graph/src/main/java/uk/gov/gchq/gaffer/graph/Graph.java
- core/store/src/main/java/uk/gov/gchq/gaffer/store/operation/handler/OperationChainHandler.java
- rest-api/spring-rest/src/main/java/uk/gov/gchq/gaffer/rest/controller/GremlinController.java
- rest-api/spring-rest/src/main/java/uk/gov/gchq/gaffer/rest/handler/GremlinWebSocketHandler.java
* change user attribute to OTEL standard `enduser.id` that can be picked up by external OTEL dashboards
* make constants for other attributes to ensure consistency
> Change OTEL user attribute

- library/tinkerpop/src/main/java/uk/gov/gchq/gaffer/tinkerpop/GafferPopGraph.java
- library/tinkerpop/src/main/java/uk/gov/gchq/gaffer/tinkerpop/process/traversal/util/GafferVertexUtils.java
- library/tinkerpop/src/test/java/uk/gov/gchq/gaffer/tinkerpop/GafferPopGraphIT.java
Fix that allows users to get the 'orphan' vertices from edges that have no associated entities. 
Also change to GetSchema op when creating a view to allow use of opOperations in GafferPop.
- Resolve #3319
> Gh-3319: Fixes ability to get orphan vertices from edges

- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedAccess.java
- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedGraphStorage.java
- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreCache.java
- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreCacheTransient.java
- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/access/predicate/FederatedGraphAccessPredicate.java
- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/access/predicate/FederatedGraphReadAccessPredicate.java
- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/access/predicate/FederatedGraphWriteAccessPredicate.java
- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/access/predicate/user/FederatedGraphReadUserPredicate.java
- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/access/predicate/user/FederatedGraphWriteUserPredicate.java
- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/operation/AddGraphWithHooks.java
- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/operation/FederatedOperation.java
- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/operation/IFederatedOperation.java
- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/operation/IFederationOperation.java
- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/operation/RemoveGraphAndDeleteAllData.java
- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/util/ContextSpecificMergeFunction.java
- store-implementation/simple-federated-store/src/main/java/uk/gov/gchq/gaffer/federated/simple/FederatedStore.java
- store-implementation/simple-federated-store/src/main/java/uk/gov/gchq/gaffer/federated/simple/operation/handler/EitherOperationHandler.java
- store-implementation/simple-federated-store/src/main/java/uk/gov/gchq/gaffer/federated/simple/operation/handler/FederatedOperationHandler.java
- store-implementation/simple-federated-store/src/main/java/uk/gov/gchq/gaffer/federated/simple/operation/handler/FederatedOutputHandler.java
- store-implementation/simple-federated-store/src/main/java/uk/gov/gchq/gaffer/federated/simple/operation/handler/get/GetSchemaHandler.java
- store-implementation/simple-federated-store/src/test/java/uk/gov/gchq/gaffer/federated/simple/operation/GetSchemaTest.java
Updates how schemas are merged to make them more robust to failure. Includes some minor related tweaks too.
- Resolve #3326
> Gh-3326: Update Schema merge federated POC

- library/tinkerpop/src/main/java/uk/gov/gchq/gaffer/tinkerpop/GafferPopGraph.java
- library/tinkerpop/src/main/java/uk/gov/gchq/gaffer/tinkerpop/GafferPopGraphVariables.java
- library/tinkerpop/src/main/java/uk/gov/gchq/gaffer/tinkerpop/process/traversal/step/GafferPopGraphStep.java
- library/tinkerpop/src/test/java/uk/gov/gchq/gaffer/tinkerpop/GafferPopFederationTests.java
- library/tinkerpop/src/test/java/uk/gov/gchq/gaffer/tinkerpop/GafferPopGraphIT.java
- library/tinkerpop/src/test/java/uk/gov/gchq/gaffer/tinkerpop/GafferPopGraphTest.java
- library/tinkerpop/src/test/resources/gafferpop-test.properties
Fixes issue of odd number of vertices being returned if lots of edges are in the Gaffer result. This is primarily due them not being filtered out in the view as they are used in the orphaned vertex check. To fix this the orphan check has been made optional and opt in so the user should be aware of the potential side effects. Also increased default limit as it was quite low.
- Resolve #3340
> Gh-3340: Misleading vertices in Gremlin

- library/tinkerpop/src/main/java/uk/gov/gchq/gaffer/tinkerpop/GafferPopEdge.java
- store-implementation/simple-federated-store/src/main/java/uk/gov/gchq/gaffer/federated/simple/FederatedUtils.java
- store-implementation/simple-federated-store/src/main/java/uk/gov/gchq/gaffer/federated/simple/operation/handler/FederatedOperationHandler.java
- store-implementation/simple-federated-store/src/main/java/uk/gov/gchq/gaffer/federated/simple/operation/handler/FederatedOutputHandler.java
- store-implementation/simple-federated-store/src/test/java/uk/gov/gchq/gaffer/federated/simple/FederatedUtilsTest.java
Adds ability to handle groups in a View that might not be relevant to a selected sub graph.
- Resolve #3342
> Gh-3342: Handle different groups in View federated poc

- store-implementation/simple-federated-store/src/main/java/uk/gov/gchq/gaffer/federated/simple/FederatedStore.java
- store-implementation/simple-federated-store/src/main/java/uk/gov/gchq/gaffer/federated/simple/operation/ChangeGraphAccess.java
- store-implementation/simple-federated-store/src/main/java/uk/gov/gchq/gaffer/federated/simple/operation/handler/misc/ChangeGraphAccessHandler.java
- store-implementation/simple-federated-store/src/test/java/uk/gov/gchq/gaffer/federated/simple/operation/ChangeGraphAccessTest.java
Adds an operation to allow changing the graph accesses of sub graphs on the new federated store.
> Gh-3344: Change graph permissions operation in federated POC

- core/store/src/main/java/uk/gov/gchq/gaffer/store/Store.java
- core/store/src/test/java/uk/gov/gchq/gaffer/store/StoreTest.java
- rest-api/common-rest/src/main/java/uk/gov/gchq/gaffer/rest/service/v2/AbstractOperationService.java
- rest-api/core-rest/src/main/java/uk/gov/gchq/gaffer/rest/service/v2/IOperationServiceV2.java
- rest-api/core-rest/src/main/java/uk/gov/gchq/gaffer/rest/service/v2/OperationServiceV2.java
- rest-api/core-rest/src/test/java/uk/gov/gchq/gaffer/rest/service/v2/JobServiceV2IT.java
- rest-api/core-rest/src/test/java/uk/gov/gchq/gaffer/rest/service/v2/OperationServiceV2IT.java
- rest-api/spring-rest/src/main/java/uk/gov/gchq/gaffer/rest/controller/OperationController.java
- rest-api/spring-rest/src/test/java/uk/gov/gchq/gaffer/rest/integration/controller/OperationControllerIT.java
Removes the job tracker from the main execute and any returned headers.
- Resolve #2478
> Gh-2478: JobTracker tracks all operations, not just jobs

- core/operation/src/main/java/uk/gov/gchq/gaffer/operation/impl/GetWalks.java
- core/store/src/main/java/uk/gov/gchq/gaffer/store/operation/handler/GetWalksHandler.java
- core/store/src/main/java/uk/gov/gchq/gaffer/store/operation/handler/OperationChainHandler.java
- store-implementation/simple-federated-store/src/main/java/uk/gov/gchq/gaffer/federated/simple/FederatedStore.java
- store-implementation/simple-federated-store/src/main/java/uk/gov/gchq/gaffer/federated/simple/access/GraphAccess.java
- store-implementation/simple-federated-store/src/main/java/uk/gov/gchq/gaffer/federated/simple/operation/handler/EitherOperationHandler.java
- store-implementation/simple-federated-store/src/test/java/uk/gov/gchq/gaffer/federated/simple/FederatedStoreIT.java
- store-implementation/simple-federated-store/src/test/java/uk/gov/gchq/gaffer/federated/simple/util/FederatedModernTestUtils.java
Fixes a few issues for `GetWalks` when running on new federated POC along with some general bug fixes for it too.
Main changes:
* `GetWalks.flatten()` no longer gives all the operations get walks will run as this removes all the information about the operation can can be very misleading in an operation chain.
* `OperationChainHandler` can now apply all operation options on the top level chain to all child operations.
* Bug fix to `GetWalks` as it did not treat an `allEdges: true` as a valid hop.
- Resolve #3351
> Gh-3351: Better GetWalks support on federated POC

- core/common-util/src/main/java/uk/gov/gchq/gaffer/commonutil/otel/OtelUtil.java
- core/graph/src/main/java/uk/gov/gchq/gaffer/graph/Graph.java
- core/store/src/main/java/uk/gov/gchq/gaffer/store/operation/handler/OperationChainHandler.java
- library/tinkerpop/src/main/java/uk/gov/gchq/gaffer/tinkerpop/GafferPopGraph.java
- library/tinkerpop/src/main/java/uk/gov/gchq/gaffer/tinkerpop/process/traversal/step/GafferPopGraphStep.java
- library/tinkerpop/src/test/java/uk/gov/gchq/gaffer/tinkerpop/GafferPopGraphIT.java
- rest-api/spring-rest/src/main/java/uk/gov/gchq/gaffer/rest/config/GremlinConfig.java
- rest-api/spring-rest/src/main/java/uk/gov/gchq/gaffer/rest/config/GremlinWebSocketConfig.java
- rest-api/spring-rest/src/main/java/uk/gov/gchq/gaffer/rest/controller/GremlinController.java
- rest-api/spring-rest/src/main/java/uk/gov/gchq/gaffer/rest/handler/GremlinWebSocketHandler.java
- rest-api/spring-rest/src/test/java/uk/gov/gchq/gaffer/rest/controller/GremlinControllerTest.java
- rest-api/spring-rest/src/test/java/uk/gov/gchq/gaffer/rest/integration/handler/GremlinWebSocketIT.java
Addresses some of the issues with passing information from the REST API to gafferpop by ensuring each request now has its own instance of the tinkerpop graph layer so the variables are unique per request. Also stops the user from being reset immediately by the custom GraphStep.
Few other minor bits of tidying and improvements to otel logging.
- Resolve #3353
> Gh-3353: Ensure user info passed in GafferPop

- core/graph/src/test/java/uk/gov/gchq/gaffer/graph/GraphTest.java
- core/graph/src/test/java/uk/gov/gchq/gaffer/integration/store/TestStore.java
- core/operation/src/main/java/uk/gov/gchq/gaffer/operation/impl/delete/DeleteElements.java
- core/store/src/main/java/uk/gov/gchq/gaffer/store/Store.java
- core/store/src/test/java/uk/gov/gchq/gaffer/store/StoreTest.java
- core/store/src/test/java/uk/gov/gchq/gaffer/store/integration/StoreIT.java
- core/store/src/test/java/uk/gov/gchq/gaffer/store/operation/handler/TestAddToGraphLibraryImpl.java
- store-implementation/accumulo-store/src/main/java/uk/gov/gchq/gaffer/accumulostore/AccumuloStore.java
- store-implementation/accumulo-store/src/main/java/uk/gov/gchq/gaffer/accumulostore/operation/handler/DeleteElementsHandler.java
- store-implementation/accumulo-store/src/test/java/uk/gov/gchq/gaffer/accumulostore/integration/delete/AbstractDeletedElementsIT.java
- store-implementation/accumulo-store/src/test/java/uk/gov/gchq/gaffer/accumulostore/operation/handler/DeleteElementsHandlerTest.java
- store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/FederatedStore.java
- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/operation/handler/impl/FederatedDeleteElementsTest.java
- store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/operation/handler/impl/FederatedGetTraitsHandlerTest.java
- store-implementation/map-store/src/main/java/uk/gov/gchq/gaffer/mapstore/MapStore.java
- store-implementation/map-store/src/main/java/uk/gov/gchq/gaffer/mapstore/impl/DeleteElementsHandler.java
- store-implementation/map-store/src/test/java/uk/gov/gchq/gaffer/mapstore/impl/DeleteElementsHandlerTest.java
- store-implementation/proxy-store/src/main/java/uk/gov/gchq/gaffer/proxystore/ProxyStore.java
- store-implementation/simple-federated-store/src/main/java/uk/gov/gchq/gaffer/federated/simple/FederatedStore.java
DeleteElements will now return a count to reflect the number of elements deleted. Additional debug logging added as well to allow users to check what is deleted.
- Resolve #3355
> DeleteElements to return count

- core/access/src/main/java/uk/gov/gchq/gaffer/access/predicate/user/NoAccessUserPredicate.java
- core/access/src/main/java/uk/gov/gchq/gaffer/access/predicate/user/UnrestrictedAccessUserPredicate.java
- store-implementation/simple-federated-store/src/main/java/uk/gov/gchq/gaffer/federated/simple/FederatedUtils.java
- store-implementation/simple-federated-store/src/main/java/uk/gov/gchq/gaffer/federated/simple/operation/handler/FederatedOperationHandler.java
- store-implementation/simple-federated-store/src/main/java/uk/gov/gchq/gaffer/federated/simple/operation/handler/FederatedOutputHandler.java
- store-implementation/simple-federated-store/src/main/java/uk/gov/gchq/gaffer/federated/simple/operation/handler/SeparateOutputHandler.java
* Simple federated store fixes from #3357 
* * Missing serializables
* * Add missing view fixing for SeparateResults handler
* * Fix OperationChain mutation
* Optimisations to follow in a separate PR
- Resolve #3350
> Gh-3350: Simple fed store fixes

- library/tinkerpop/src/main/java/uk/gov/gchq/gaffer/tinkerpop/GafferPopEdge.java
- library/tinkerpop/src/test/java/uk/gov/gchq/gaffer/tinkerpop/GafferPopGraphIT.java
Stop inV/outV performing a full vertex lookup
Add new methods for doing this when we want to traverse an Edge
- Resolve #3359
> Gh-3359: Reduce number of vertex lookups for edges
